import '../models/content_model.dart';

class SampleDataEN {
  static ContentData getSampleContent() {
    return ContentData(sections: [
      ContentSection(
        id: 'chapter1',
        title: 'My First Visit to the Gynecologist',
        imageUrl: '',
        categories: [
          ContentCategory(
            id: '1.1',
            title: 'Introduction to Gynecology',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.1.1',
                question: 'What does a gynecologist do?',
                answer: 'A gynecologist takes care of women\'s health - particularly issues around menstruation, pregnancy, childbirth, and menopause.',
                categoryId: '1.1',
              ),
              ContentQuestion(
                id: '1.1.2',
                question: 'How do I find a suitable gynecologist?',
                answer: 'You can look for reviews online or ask friends and family. The important thing is that you feel comfortable and understood.',
                categoryId: '1.1',
              ),
              ContentQuestion(
                id: '1.1.3',
                question: 'What is a gynecological consultation?',
                answer: 'It\'s a discussion or examination with your gynecologist. It covers your health, questions about contraception, periods, or pregnancy.',
                categoryId: '1.1',
              ),
            ],
          ),
          ContentCategory(
            id: '1.2',
            title: 'First Steps When Suspecting Pregnancy',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.2.1',
                question: 'What happens during the first consultation?',
                answer: 'The doctor asks questions, might do an ultrasound or take blood samples to see if you\'re pregnant and how you\'re doing.',
                categoryId: '1.2',
              ),
              ContentQuestion(
                id: '1.2.2',
                question: 'How do I prepare for a gynecological examination?',
                answer: 'You don\'t need to do anything special - just be clean. You can shower beforehand, but don\'t need to shave or anything similar.',
                categoryId: '1.2',
              ),
              ContentQuestion(
                id: '1.2.3',
                question: 'What terms should I know?',
                answer: 'Important terms include: cycle (menstruation), ovulation, ultrasound, uterus, and hormone. Your doctor will explain everything in detail.',
                categoryId: '1.2',
              ),
              ContentQuestion(
                id: '1.2.4',
                question: 'What should I not forget?',
                answer: 'Bring your ID, health insurance card, and any questions you want to ask. Write down everything that\'s important to you.',
                categoryId: '1.2',
              ),
            ],
          ),
          ContentCategory(
            id: '1.3',
            title: 'Basics of the Female Body',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.3.1',
                question: 'What does the cycle mean?',
                answer: 'The cycle is the time from one menstruation to the next. It shows that your body is ready to become pregnant.',
                categoryId: '1.3',
              ),
              ContentQuestion(
                id: '1.3.2',
                question: 'What role does the uterus play?',
                answer: 'The uterus is where the baby grows. It protects and nourishes the baby during pregnancy.',
                categoryId: '1.3',
              ),
              ContentQuestion(
                id: '1.3.3',
                question: 'What are hormones and why are they important?',
                answer: 'Hormones are messenger substances in your body. They control your period, ovulation, and pregnancy.',
                categoryId: '1.3',
              ),
              ContentQuestion(
                id: '1.3.4',
                question: 'What is folic acid and why do you need it?',
                answer: 'Folic acid is a vitamin. It helps the baby develop healthily - especially during the first weeks of pregnancy.',
                categoryId: '1.3',
              ),
            ],
          ),
          ContentCategory(
            id: '1.4',
            title: 'Care During Pregnancy',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.4.2',
                question: 'When should I go to the hospital - and why?',
                answer: 'If you have severe pain, bleeding, or can no longer feel your baby moving. You also go to the hospital for childbirth.',
                categoryId: '1.4',
              ),
              ContentQuestion(
                id: '1.4.3',
                question: 'Who can accompany me during pregnancy?',
                answer: 'You can decide who is with you - your partner, a friend, or someone from your family.',
                categoryId: '1.4',
              ),
              ContentQuestion(
                id: '1.4.4',
                question: 'What accompanying illnesses can occur?',
                answer: 'Some women develop diabetes, high blood pressure, or back pain. Your doctor will regularly check on your health.',
                categoryId: '1.4',
              ),
            ],
          ),
          ContentCategory(
            id: '1.5',
            title: 'Emotional and Cultural Aspects',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.5.1',
                question: 'Psychological support: How do I deal with uncertainties and fears?',
                answer: 'Talk to your doctor or a counselor. It\'s completely normal to be afraid sometimes. You are not alone.',
                categoryId: '1.5',
              ),
              ContentQuestion(
                id: '1.5.2',
                question: 'Cultural differences in pregnancy care',
                answer: 'Different cultures have their own rituals. What matters is that you feel comfortable with the care - speak openly with your doctor.',
                categoryId: '1.5',
              ),
            ],
          ),
          ContentCategory(
            id: '1.6',
            title: 'Practical Questions',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.6.1',
                question: 'How much does a pregnancy cost?',
                answer: 'Health insurance covers most examinations. Some extras like 3D ultrasound cost extra.',
                categoryId: '1.6',
              ),
              ContentQuestion(
                id: '1.6.2',
                question: 'What rights do I have as a pregnant woman?',
                answer: 'You have rights to maternity protection, doctor\'s appointments during working hours, and protection against dismissal.',
                categoryId: '1.6',
              ),
              ContentQuestion(
                id: '1.6.3',
                question: 'What is maternity protection?',
                answer: 'It\'s a legal break before and after birth. During this time, you don\'t have to work and still receive payment.',
                categoryId: '1.6',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter2',
        title: 'Desire for Children & Preparation for Pregnancy',
        imageUrl: '',
        categories: [
          ContentCategory(
            id: '2.1',
            title: 'Basics of Fertility',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.1.1',
                question: 'What does fertility mean - and what does it depend on?',
                answer: 'Fertility means you can become pregnant. It depends on your cycle, age, lifestyle, and health.',
                categoryId: '2.1',
              ),
              ContentQuestion(
                id: '2.1.2',
                question: 'How does age affect fertility?',
                answer: 'As you get older, it becomes more difficult to get pregnant - especially from your mid-30s. The quality of eggs decreases.',
                categoryId: '2.1',
              ),
              ContentQuestion(
                id: '2.1.3',
                question: 'What role does the partner play in family planning?',
                answer: 'Sperm quality is also important. A healthy lifestyle and examinations help assess the partner\'s fertility.',
                categoryId: '2.1',
              ),
              ContentQuestion(
                id: '2.1.4',
                question: 'Recognizing ovulation and fertile days (including cycle tracking)',
                answer: 'You can observe your cycle, measure temperature, or use ovulation tests. This helps you find out your fertile days.',
                categoryId: '2.1',
              ),
            ],
          ),
          ContentCategory(
            id: '2.2',
            title: 'Physical & Mental Preparation',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.2.1',
                question: 'How do I prepare my body for pregnancy?',
                answer: 'Eat healthily, exercise regularly, and take folic acid. Regular doctor\'s visits for check-ups are also useful.',
                categoryId: '2.2',
              ),
              ContentQuestion(
                id: '2.2.2',
                question: 'What supports - and what inhibits - my fertility?',
                answer: 'Good: healthy diet, low stress, no smoking. Bad effects come from alcohol, being overweight, or lack of sleep.',
                categoryId: '2.2',
              ),
              ContentQuestion(
                id: '2.2.3',
                question: 'How important is mental health when wanting a child?',
                answer: 'Very important. Stress can disrupt hormone balance. Relaxation, conversations, and support help.',
                categoryId: '2.2',
              ),
              ContentQuestion(
                id: '2.2.4',
                question: 'Are there natural ways to increase fertility?',
                answer: 'Yes, e.g., herbal remedies, acupuncture, or certain teas. It\'s important to discuss this with a doctor beforehand.',
                categoryId: '2.2',
              ),
            ],
          ),
          ContentCategory(
            id: '2.3',
            title: 'Medical Clarification & Help',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.3.1',
                question: 'What examinations make sense before pregnancy?',
                answer: 'A blood count, hormone status, immunization status, and check for infections are helpful to be well prepared.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.2',
                question: 'What to do if we can\'t conceive?',
                answer: 'After a year without success, you should seek advice from your gynecologist or a fertility clinic.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.3',
                question: 'When to do what? Artificial insemination - what methods are available?',
                answer: 'There\'s insemination, IVF, and ICSI. The suitable method depends on the cause of infertility.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.4',
                question: 'What is a fertility clinic?',
                answer: 'It\'s a specialized practice that supports couples with unfulfilled desire for children and offers modern treatments.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.5',
                question: 'What can the partner contribute medically?',
                answer: 'A sperm analysis shows the condition of the sperm. Hormone or blood tests may also be useful.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.6',
                question: 'What to do about repeated miscarriages?',
                answer: 'A doctor can investigate causes such as clotting disorders or hormone problems and provide targeted treatment.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.7',
                question: 'Can I get pregnant despite illness or chronic condition?',
                answer: 'Often yes - but good medical care is important to keep mother and child healthy.',
                categoryId: '2.3',
              ),
            ],
          ),
          ContentCategory(
            id: '2.4',
            title: 'Personal and Partnership Considerations',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.4.1',
                question: 'When is the right time for a child?',
                answer: 'The perfect moment rarely exists. When you feel physically and emotionally ready, it\'s usually the right time.',
                categoryId: '2.4',
              ),
              ContentQuestion(
                id: '2.4.2',
                question: 'How can I prepare emotionally for a child?',
                answer: 'Talk about your wishes and fears, gather information, and take your time. Talking with others also helps.',
                categoryId: '2.4',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter3',
        title: 'Pregnancy',
        imageUrl: '',
        categories: [
          ContentCategory(
            id: '3.1',
            title: 'Basics of Pregnancy',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.1.1',
                question: 'What is pregnancy and how does it occur?',
                answer: 'Pregnancy begins when an egg combines with a sperm and implants in the uterus.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.2',
                question: 'What is an embryo and what is a fetus?',
                answer: 'In the first weeks, the baby is called an embryo. From the 9th week, it\'s called a fetus - by then, many organs have already formed.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.3',
                question: 'How long does pregnancy last?',
                answer: 'A pregnancy lasts about 40 weeks or 9 months - counted from the first day of your last period.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.4',
                question: 'What is a trimester?',
                answer: 'Pregnancy is divided into three parts - each trimester lasts about three months and has typical changes.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.5',
                question: 'How does the baby develop week by week?',
                answer: 'Each week the baby grows - first organs form, then arms, legs, heart, brain, and finally it gains weight.',
                categoryId: '3.1',
              ),
            ],
          ),
          ContentCategory(
            id: '3.2',
            title: 'First Signs & Confirmation',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.2.1',
                question: 'How do I know I\'m pregnant?',
                answer: 'Typical signs include: missed period, nausea, breast tenderness, fatigue, or a different feeling in your body.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.2',
                question: 'How do I take a pregnancy test?',
                answer: 'You can buy a test at the pharmacy. You take it with urine, preferably in the morning. If it shows positive, you\'re probably pregnant.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.3',
                question: 'What does a positive pregnancy test mean?',
                answer: 'A positive test indicates that you\'re very likely pregnant. A visit to the gynecologist provides certainty.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.4',
                question: 'What do I do after a positive test?',
                answer: 'Make an appointment with your gynecologist. The pregnancy will be confirmed there and everything else discussed.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.5',
                question: 'When can you see the baby on ultrasound?',
                answer: 'From about the 6th week, you can see something on ultrasound - like a small gestational sac or already the heartbeat.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.6',
                question: 'What is the hCG hormone?',
                answer: 'hCG is the pregnancy hormone. It rises sharply in the first weeks and ensures that the pregnancy continues.',
                categoryId: '3.2',
              ),
            ],
          ),
          ContentCategory(
            id: '3.3',
            title: 'Physical Changes & Health',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.3.1',
                question: 'What physical changes do I feel at the beginning?',
                answer: 'Many women feel tired, have sensitive breasts, mild nausea, or pulling in the lower abdomen. Every body reacts differently.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.2',
                question: 'Is nausea in early pregnancy normal?',
                answer: 'Yes, it\'s very common. It usually comes from hormones and is often stronger in the morning. It usually passes after the 3rd month.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.3',
                question: 'What can I eat - and what not?',
                answer: 'Eating healthy is important. Avoid raw meat, raw fish, alcohol, and certain cheeses. Your doctor will give you a list.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.4',
                question: 'Is exercise allowed during pregnancy?',
                answer: 'Yes, movement is good - e.g., walking, swimming, or yoga. But ask your doctor if it\'s okay in your case.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.5',
                question: 'Can I continue working when I\'m pregnant?',
                answer: 'In most cases yes - if there\'s no danger. Your doctor and employer will help you adapt your workplace.',
                categoryId: '3.3',
              ),
            ],
          ),
          ContentCategory(
            id: '3.4',
            title: 'Documentation & Social Aspects',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.4.1',
                question: 'When should I tell my family or at work that I\'m pregnant?',
                answer: 'That\'s your decision. Many wait until the 12th week. At work, you should mention it when you need protection.',
                categoryId: '3.4',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter4',
        title: 'Care During Pregnancy',
        imageUrl: '',
        categories: [
          ContentCategory(
            id: '4.1',
            title: 'Caregivers & Roles',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.1.1',
                question: 'Who takes care of me during pregnancy?',
                answer: 'Usually it\'s your gynecologist, sometimes also a midwife. Both often work hand in hand.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.2',
                question: 'What does the gynecologist do - what does the midwife do?',
                answer: 'The doctor performs medical examinations, the midwife advises you, accompanies you emotionally and often during birth.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.3',
                question: 'What is a resident midwife?',
                answer: 'This is a midwife who cares for you before, during, and after birth - also in the hospital that you choose together.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.4',
                question: 'What is a doula?',
                answer: 'A doula is an experienced woman who provides additional emotional support - but she doesn\'t replace a midwife or doctor.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.5',
                question: 'How do I find a midwife?',
                answer: 'Ask early at your health insurance, online, or friends. Many midwives get booked quickly.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.6',
                question: 'Who accompanies me to the birth?',
                answer: 'You can decide who should be with you - partner, friend, midwife, or doula. What matters is that you feel comfortable.',
                categoryId: '4.1',
              ),
            ],
          ),
          ContentCategory(
            id: '4.2',
            title: 'Prenatal Care & Diagnostics',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.2.1',
                question: 'What are prenatal check-ups - when and how often?',
                answer: 'They take place every 4 weeks, later more often. Your abdomen, urine, blood pressure, and the baby are checked via ultrasound.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.2',
                question: 'What ultrasound examinations are there?',
                answer: 'There are three standard ultrasounds during pregnancy. Additionally, you can have 3D or 4D ultrasound privately.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.3',
                question: 'What is documented in the maternity record?',
                answer: 'The maternity record contains important info about you, the baby, examinations, and risks - it accompanies you throughout pregnancy.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.4',
                question: 'Why are blood type and Rhesus factor determined?',
                answer: 'This is important if there\'s bleeding or during birth. Certain combinations require a special injection.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.5',
                question: 'What is a toxoplasmosis test?',
                answer: 'The test shows if you have an infection that could harm the baby. It\'s not always free, but often useful.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.6',
                question: 'What is a rubella or toxoplasmosis titer?',
                answer: 'It\'s a blood value that shows if you\'re protected against rubella or toxoplasmosis - important for the baby\'s health.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.7',
                question: 'Which blood values are important?',
                answer: 'For example, iron, blood sugar, thyroid, and certain antibodies - they show if your body is working well for pregnancy.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.8',
                question: 'Which tests are offered upon request?',
                answer: 'Additional tests like nuchal translucency measurement or blood tests for genetic features can be done voluntarily - often for a fee.',
                categoryId: '4.2',
              ),
            ],
          ),
          ContentCategory(
            id: '4.3',
            title: 'Medical Monitoring & Special Tests',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.3.1',
                question: 'What is pregnancy-related hypertension and how is it monitored?',
                answer: 'This is high blood pressure during pregnancy. It\'s measured at each check-up because it can be dangerous.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.2',
                question: 'What is the glucose tolerance test (sugar load test)?',
                answer: 'It shows if you have gestational diabetes. You drink a sugar solution, then your blood sugar is checked.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.3',
                question: 'What is gestational diabetes and how is it monitored?',
                answer: 'It\'s diabetes that develops during pregnancy. It\'s treated with diet, exercise, and sometimes insulin.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.4',
                question: 'How does a CTG (cardiotocography) work?',
                answer: 'A CTG measures the baby\'s heartbeat and your contractions. It\'s regularly done towards the end of pregnancy.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.5',
                question: 'What is an organ screening?',
                answer: 'During organ screening, the doctor checks via ultrasound whether all the baby\'s organs are developing healthily.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.6',
                question: 'What does a 3D/4D ultrasound provide?',
                answer: 'It shows the baby in spatial representation. Sometimes you can recognize features better - but often it\'s just a nice extra.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.7',
                question: 'What is a high-risk pregnancy - what does it mean for me?',
                answer: 'It means that you or your baby need special observation - e.g., due to age, illness, or previous problems. You get more care.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.8',
                question: 'How does care work when there are complications?',
                answer: 'You\'ll be closely monitored - e.g., more frequent examinations or hospital stays to keep you and the baby healthy.',
                categoryId: '4.3',
              ),
            ],
          ),
          ContentCategory(
            id: '4.4',
            title: 'Birth Preparation & Organization',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.4.1',
                question: 'When should I decide on a hospital?',
                answer: 'Best by the 20th week - many hospitals fill up early. Then you can also register for the birth there.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.2',
                question: 'How does registration for birth at the hospital work?',
                answer: 'You register by phone or online. Some hospitals invite you to an information evening or have an on-site meeting.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.3',
                question: 'What\'s special about a multiple pregnancy?',
                answer: 'You\'ll be examined more frequently because twins or more babies have a higher risk. The birth is often planned more carefully.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.4',
                question: 'What does the final examination shortly before birth include?',
                answer: 'The doctor checks the baby\'s position and weight, contractions, cervix, and if everything is ready for birth.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.5',
                question: 'What\'s the difference between outpatient and inpatient care?',
                answer: 'Outpatient means you go home soon after birth. Inpatient means you stay in the hospital for a few days.',
                categoryId: '4.4',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter5',
        title: 'Preparation for Birth',
        imageUrl: '',
        categories: [
          ContentCategory(
            id: '5.1',
            title: 'Getting Started with Birth Preparation',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.1.1',
                question: 'When do I start preparing for birth?',
                answer: 'Best from the 25th week of pregnancy. This gives you enough time to prepare physically and mentally.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.2',
                question: 'What is a birth preparation course?',
                answer: 'In this course, you learn what happens during birth, how to relax, and how your partner can support you.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.3',
                question: 'What do I learn there?',
                answer: 'You learn breathing techniques, birth positions, info about birth, postpartum period, and how to handle pain.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.4',
                question: 'Does the partner also need preparation?',
                answer: 'Yes, partners can also learn a lot - how to help, support, and be there during birth.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.5',
                question: 'What role does the midwife play before birth?',
                answer: 'She accompanies you, answers questions, prepares you for birth, and helps reduce fears.',
                categoryId: '5.1',
              ),
            ],
          ),
          ContentCategory(
            id: '5.2',
            title: 'Practical Matters & Organization',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.2.1',
                question: 'What belongs in the hospital bag and when do I pack it?',
                answer: 'Pack it about 4 weeks before your due date. Include: clothing, toiletries, documents, snacks, baby essentials.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.3',
                question: 'What is a birth plan - and how do I write it?',
                answer: 'In the plan, you note wishes for birth: e.g., pain medication, positions, who should be present. It\'s a help for the hospital team.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.4',
                question: 'What\'s important for choosing the birthplace?',
                answer: 'Important factors are proximity, facilities, handling of emergencies, and your gut feeling. Hospital, birth center, or home - all are possible.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.5',
                question: 'Birth in hospital, birth center, or at home - what suits me?',
                answer: 'It depends on your health, your wishes, and your safety. Talk to your doctor or midwife about it.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.6',
                question: 'What is a risk in a home birth?',
                answer: 'There\'s less medical equipment than in a hospital. In case of complications, you must be able to switch quickly.',
                categoryId: '5.2',
              ),
            ],
          ),
          ContentCategory(
            id: '5.3',
            title: 'Mental & Physical Preparation',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.3.1',
                question: 'How do I mentally prepare for birth?',
                answer: 'Talk about fears, get informed, practice relaxation, and trust your body. Courses and conversations also help.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.2',
                question: 'What can I do about fears before birth?',
                answer: 'Talk to your midwife, learn relaxation techniques, and speak with other mothers about their experiences.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.3',
                question: 'Which relaxation methods help?',
                answer: 'Breathing exercises, meditation, massages, calming music, and movement can help you stay calm and composed.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.4',
                question: 'What signs indicate that birth is imminent?',
                answer: 'Signs include: regular contractions, water breaking, mucus plug discharge, or back pain. Then it could start soon.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.5',
                question: 'What is the nesting instinct?',
                answer: 'Shortly before birth, many women feel the urge to clean and prepare everything - this is completely normal.',
                categoryId: '5.3',
              ),
            ],
          ),
          ContentCategory(
            id: '5.4',
            title: 'Physical Preparation & Exercises',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.4.1',
                question: 'What role does movement play in late pregnancy?',
                answer: 'It strengthens your body, promotes circulation, and can help you sleep better and prepare for birth.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.2',
                question: 'Which exercises prepare for birth?',
                answer: 'Good ones are: pelvic floor exercises, breathing techniques, light yoga or stretching exercises. Your midwife will show you what fits.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.3',
                question: 'Which birth positions can I practice?',
                answer: 'For example: all fours, squatting, standing, lying. Try what feels good - your body will guide you.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.4',
                question: 'How can I prepare my pelvic floor muscles?',
                answer: 'With special exercises, you train the muscles in the pelvis - they help during birth and prevent later urinary incontinence.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.5',
                question: 'What is perineal massage and what is it for?',
                answer: 'It makes the tissue more elastic and can help prevent perineal tears during birth. You can start from week 34.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.6',
                question: 'What happens during birth-preparing acupuncture?',
                answer: 'Fine needles are placed at certain points. This is supposed to prepare the body for birth and relieve pain.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.7',
                question: 'What is a CTG and when is it done?',
                answer: 'A CTG measures the baby\'s heartbeat and your contractions. It\'s usually done regularly from the 30th week onwards.',
                categoryId: '5.4',
              ),
            ],
          ),
          ContentCategory(
            id: '5.5',
            title: 'Special Preparation Situations',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.5.1',
                question: 'What\'s different with multiple pregnancies in preparation?',
                answer: 'The birth is planned more carefully, there are more check-ups, and often a C-section is necessary - your hospital will help you with this.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.2',
                question: 'How can I prepare for a premature birth?',
                answer: 'Discuss everything with your doctor and hospital. Important are rest, close monitoring, and information on premature baby care.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.3',
                question: 'What if the baby is in breech position?',
                answer: 'Sometimes the baby can still turn. There are special exercises or external cephalic version by the doctor.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.4',
                question: 'How do I prepare for a planned C-section?',
                answer: 'You\'ll be well informed. The hospital explains everything and you usually get an appointment for the operation in advance.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.5',
                question: 'Who helps me prepare if I\'m alone?',
                answer: 'Midwives, counseling centers, or friends can support you. You\'re not alone - there\'s help for you.',
                categoryId: '5.5',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter6',
        title: 'Birth - What to Expect',
        imageUrl: '',
        categories: [
          ContentCategory(
            id: '6.1',
            title: 'Arrival & Admission',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.1.1',
                question: 'When should I go to the hospital or birth center?',
                answer: 'When contractions come regularly, your water breaks, or you have pain, you should make your way there.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.2',
                question: 'What happens during admission for birth?',
                answer: 'You\'ll be examined, asked how you\'re doing, given a CTG, and they\'ll check how far along the birth is.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.3',
                question: 'What examinations are done at the beginning?',
                answer: 'Usually a CTG, palpation of the abdomen, vaginal examination, and sometimes an ultrasound.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.4',
                question: 'What is the cervix and how is it checked?',
                answer: 'The cervix is the exit of the uterus. It is checked for dilation during a vaginal examination.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.5',
                question: 'What is a CTG and why is it important?',
                answer: 'A CTG measures your baby\'s heartbeat and your contractions. This shows how the baby is doing.',
                categoryId: '6.1',
              ),
            ],
          ),
          ContentCategory(
            id: '6.2',
            title: 'Pain Relief & Birth Methods',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.2.1',
                question: 'What pain medications are available during birth?',
                answer: 'There are many options: breathing techniques, heat, massage, pain medications, nitrous oxide, or an epidural.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.2',
                question: 'What is an epidural (PDA)?',
                answer: 'An epidural is an injection in your back that numbs the lower body - so you barely feel the contractions.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.3',
                question: 'What is a spinal anesthesia?',
                answer: 'It works faster than an epidural and is often used for planned C-sections.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.4',
                question: 'What is a water birth and how does it work?',
                answer: 'You give birth in a special tub. The warm water relaxes and can reduce pain.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.5',
                question: 'What natural methods of pain relief are there?',
                answer: 'Movement, breathing techniques, massage, water, birthing stool, or partner help - all can help you.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.6',
                question: 'What if I\'m afraid of childbirth?',
                answer: 'Talk about it with your midwife. There\'s birth preparation, hypnobirthing, and support for you.',
                categoryId: '6.2',
              ),
            ],
          ),
          ContentCategory(
            id: '6.3',
            title: 'Vaginal Birth Process',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.3.1',
                question: 'How does a vaginal birth proceed - step by step?',
                answer: 'First, the cervix and uterus open. Then comes the pushing phase and finally the baby is born.',
                categoryId: '6.3',
              ),
              ContentQuestion(
                id: '6.3.2',
                question: 'What positions can I take during birth?',
                answer: 'Standing, sitting, kneeling, lying - you can choose what\'s most comfortable for you.',
                categoryId: '6.3',
              ),
              ContentQuestion(
                id: '6.3.3',
                question: 'What happens during pushing?',
                answer: 'You actively help push the baby out - guided by midwife or doctor.',
                categoryId: '6.3',
              ),
              ContentQuestion(
                id: '6.3.4',
                question: 'What happens immediately after the baby is born?',
                answer: 'The baby comes onto your belly, the umbilical cord is cut, and you usually deliver the placenta.',
                categoryId: '6.3',
              ),
            ],
          ),
          ContentCategory(
            id: '6.4',
            title: 'Physical Consequences & Care',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.4.1',
                question: 'What is an episiotomy and when is it done?',
                answer: 'An episiotomy is a small cut at the vaginal opening - it\'s only done when necessary, e.g., if the baby is at risk.',
                categoryId: '6.4',
              ),
              ContentQuestion(
                id: '6.4.2',
                question: 'What is a perineal tear?',
                answer: 'The perineum can tear during birth - it usually heals well and is stitched by the doctor immediately.',
                categoryId: '6.4',
              ),
              ContentQuestion(
                id: '6.4.3',
                question: 'How is a perineal tear treated?',
                answer: 'The tear is stitched with thread after birth, which later dissolves on its own. Pain medication helps with healing.',
                categoryId: '6.4',
              ),
              ContentQuestion(
                id: '6.4.4',
                question: 'What happens to the placenta after birth?',
                answer: 'It\'s usually delivered shortly after the baby - this is called afterbirth. The doctor checks if it\'s complete.',
                categoryId: '6.4',
              ),
            ],
          ),
          ContentCategory(
            id: '6.5',
            title: 'Baby & First Bonding',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.5.1',
                question: 'What is bonding after birth?',
                answer: 'Bonding is the first cuddling with your baby - it strengthens your connection and provides security and warmth.',
                categoryId: '6.5',
              ),
              ContentQuestion(
                id: '6.5.2',
                question: 'How is the baby examined after birth?',
                answer: 'The doctor checks breathing, heartbeat, reflexes, and appearance - all quickly and lovingly.',
                categoryId: '6.5',
              ),
              ContentQuestion(
                id: '6.5.3',
                question: 'What is the APGAR score?',
                answer: 'It evaluates Appearance, Pulse, Grimace, Activity, and Respiration - immediately after birth, after 5 and 10 minutes.',
                categoryId: '6.5',
              ),
            ],
          ),
          ContentCategory(
            id: '6.6',
            title: 'Special Situations & Complications',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.6.1',
                question: 'What role does the midwife play during birth?',
                answer: 'She\'s the most important companion, supports you during contractions, observes you and the baby, and helps with decisions.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.2',
                question: 'What is arrest of labor?',
                answer: 'When the cervix stops dilating or the baby doesn\'t move down further, it\'s called an arrest - then action is taken.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.3',
                question: 'What happens during a vacuum extraction?',
                answer: 'A small cup is attached to the baby\'s head to help with the final part of birth - usually harmless for the child.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.4',
                question: 'When is a forceps delivery necessary?',
                answer: 'If the baby is in distress or needs to be delivered quickly, forceps can help gently pull it out.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.5',
                question: 'When and how is a C-section performed?',
                answer: 'When normal birth isn\'t possible or there\'s a risk. The baby is delivered through an abdominal incision.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.6',
                question: 'What\'s the difference between planned and emergency C-section?',
                answer: 'A planned C-section takes place before labor begins. An emergency C-section happens when complications arise during birth.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.7',
                question: 'What does precipitous birth mean?',
                answer: 'It\'s a very fast birth where everything happens suddenly - it\'s rare but usually not dangerous.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.8',
                question: 'What is an outpatient birth?',
                answer: 'You stay only a few hours after birth in the hospital and then go home - with midwife support.',
                categoryId: '6.6',
              ),
            ],
          ),
        ],
      ),
    ]);
  }
}