import '../models/content_model.dart';

class SampleDataDE {
  static ContentData getSampleContent() {
    return ContentData(sections: [
      ContentSection(
        id: 'chapter1',
        title: 'Mein erster Besuch in der gynäkologischen Praxis',
        imageUrl: 'assets/icons/chapter1.png',
        categories: [
          ContentCategory(
            id: '1.1',
            title: 'Einführung in die Gynäkologie',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.1.1',
                question: 'Was macht ein Gynäkologe?',
                answer: 'Ein Gynäkologe kümmert sich um die Gesundheit von Frauen – besonders um die Themen rund um die Regelblutung, Schwangerschaft, Geburt und Wechseljahre.',
                categoryId: '1.1',
              ),
              ContentQuestion(
                id: '1.1.2',
                question: 'Wie finde ich eine passende Frauenärztin oder einen passenden Frauenarzt?',
                answer: 'Du kannst im Internet nach Bewertungen schauen oder Freunde und Familie fragen. Wichtig ist, dass du dich wohl und verstanden fühlst.',
                categoryId: '1.1',
              ),
              ContentQuestion(
                id: '1.1.3',
                question: 'Was ist eine gynäkologische Konsultation?',
                answer: 'Das ist ein Gespräch oder eine Untersuchung beim Frauenarzt. Es geht um deine Gesundheit, Fragen zur Verhütung, Regel oder Schwangerschaft.',
                categoryId: '1.1',
              ),
            ],
          ),
          ContentCategory(
            id: '1.2',
            title: 'Erste Schritte bei Schwangerschaftsverdacht',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.2.1',
                question: 'Was passiert bei der ersten Konsultation?',
                answer: 'Der Arzt stellt Fragen, macht vielleicht einen Ultraschall oder nimmt Blut ab, um zu sehen, ob du schwanger bist und wie es dir geht.',
                categoryId: '1.2',
              ),
              ContentQuestion(
                id: '1.2.2',
                question: 'Wie bereite ich mich auf eine gynäkologische Untersuchung vor?',
                answer: 'Du brauchst nichts Besonderes tun – einfach sauber sein. Du kannst vorher duschen, musst aber nicht extra rasieren oder ähnliches.',
                categoryId: '1.2',
              ),
              ContentQuestion(
                id: '1.2.3',
                question: 'Welche Begriffe sollte ich kennen?',
                answer: 'Wichtige Begriffe sind: Zyklus (Menstruation), Eisprung, Ultraschall, Gebärmutter und Hormon. Dein Arzt erklärt dir aber auch alles genau.',
                categoryId: '1.2',
              ),
              ContentQuestion(
                id: '1.2.4',
                question: 'Was darf ich nicht vergessen?',
                answer: 'Bring deinen Ausweis, deine Krankenkassenkarte und Fragen mit, die du stellen möchtest. Schreib dir alles auf, was dir wichtig ist.',
                categoryId: '1.2',
              ),
            ],
          ),
          ContentCategory(
            id: '1.3',
            title: 'Grundlagen des weiblichen Körpers',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.3.1',
                question: 'Was bedeutet der Zyklus?',
                answer: 'Der Zyklus ist die Zeit von einer Monatsblutung bis zur nächsten. Er zeigt, dass dein Körper bereit ist, schwanger zu werden.',
                categoryId: '1.3',
              ),
              ContentQuestion(
                id: '1.3.2',
                question: 'Welche Rolle spielt die Gebärmutter?',
                answer: 'Die Gebärmutter ist der Ort, wo das Baby wächst. Sie schützt und versorgt das Baby während der Schwangerschaft.',
                categoryId: '1.3',
              ),
              ContentQuestion(
                id: '1.3.3',
                question: 'Was sind Hormone und warum sind sie wichtig?',
                answer: 'Hormone sind Botenstoffe in deinem Körper. Sie steuern deine Regel, deinen Eisprung und auch die Schwangerschaft.',
                categoryId: '1.3',
              ),
              ContentQuestion(
                id: '1.3.4',
                question: 'Was ist Folsäure und wozu braucht man sie?',
                answer: 'Folsäure ist ein Vitamin. Es hilft dem Baby, sich gesund zu entwickeln – vor allem in den ersten Wochen der Schwangerschaft.',
                categoryId: '1.3',
              ),
            ],
          ),
          ContentCategory(
            id: '1.4',
            title: 'Betreuung während der Schwangerschaft',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.4.2',
                question: 'Wann gehe ich ins Krankenhaus – und warum?',
                answer: 'Wenn du starke Schmerzen hast, Blutungen oder dein Baby nicht mehr spürst. Auch zur Geburt gehst du ins Krankenhaus.',
                categoryId: '1.4',
              ),
              ContentQuestion(
                id: '1.4.3',
                question: 'Wer darf mich während der Schwangerschaft begleiten?',
                answer: 'Du darfst entscheiden, wer bei dir ist – dein Partner, eine Freundin oder jemand aus der Familie.',
                categoryId: '1.4',
              ),
              ContentQuestion(
                id: '1.4.4',
                question: 'Welche begleitenden Erkrankungen können auftreten?',
                answer: 'Manche Frauen bekommen z. B. Diabetes, Bluthochdruck oder Rückenschmerzen. Dein Arzt schaut regelmäßig nach deiner Gesundheit.',
                categoryId: '1.4',
              ),
            ],
          ),
          ContentCategory(
            id: '1.5',
            title: 'Emotionale und kulturelle Aspekte',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.5.1',
                question: 'Psychologische Unterstützung: Wie gehe ich mit Unsicherheiten und Ängsten um?',
                answer: 'Sprich mit deinem Arzt oder einer Beraterin. Es ist ganz normal, manchmal Angst zu haben. Du bist nicht allein.',
                categoryId: '1.5',
              ),
              ContentQuestion(
                id: '1.5.2',
                question: 'Kulturelle Unterschiede in der Schwangerschaftsbetreuung',
                answer: 'Verschiedene Kulturen haben eigene Rituale. Wichtig ist, dass du dich mit der Betreuung wohlfühlst – sprich offen mit deinem Arzt.',
                categoryId: '1.5',
              ),
            ],
          ),
          ContentCategory(
            id: '1.6',
            title: 'Praktische Fragen',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.6.1',
                question: 'Was kostet eine Schwangerschaft?',
                answer: 'Die meisten Untersuchungen zahlt die Krankenkasse. Manche Extras wie 3D-Ultraschall kosten extra.',
                categoryId: '1.6',
              ),
              ContentQuestion(
                id: '1.6.2',
                question: 'Welche Rechte habe ich als schwangere Frau?',
                answer: 'Du hast z. B. Recht auf Mutterschutz, Arztbesuche in der Arbeitszeit und Schutz vor Kündigung.',
                categoryId: '1.6',
              ),
              ContentQuestion(
                id: '1.6.3',
                question: 'Was ist Mutterschutz?',
                answer: 'Das ist eine gesetzliche Pause vor und nach der Geburt. In dieser Zeit musst du nicht arbeiten und bekommst weiter Geld.',
                categoryId: '1.6',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter2',
        title: 'Kinderwunsch & Vorbereitung auf die Schwangerschaft',
        imageUrl: 'assets/icons/chapter2.png',
        categories: [
          ContentCategory(
            id: '2.1',
            title: 'Grundlagen der Fruchtbarkeit',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.1.1',
                question: 'Was bedeutet Fruchtbarkeit – und wovon hängt sie ab?',
                answer: 'Fruchtbarkeit heißt, dass du schwanger werden kannst. Sie hängt von deinem Zyklus, deinem Alter, deinem Lebensstil und der Gesundheit ab.',
                categoryId: '2.1',
              ),
              ContentQuestion(
                id: '2.1.2',
                question: 'Wie wirkt sich das Alter auf die Fruchtbarkeit aus?',
                answer: 'Mit zunehmendem Alter wird es schwieriger, schwanger zu werden – vor allem ab Mitte 30. Die Qualität der Eizellen nimmt ab.',
                categoryId: '2.1',
              ),
              ContentQuestion(
                id: '2.1.3',
                question: 'Welche Rolle spielt der Partner bei der Kinderwunschplanung?',
                answer: 'Auch die Spermienqualität ist wichtig. Ein gesunder Lebensstil und Untersuchungen helfen, die Fruchtbarkeit des Partners zu beurteilen.',
                categoryId: '2.1',
              ),
              ContentQuestion(
                id: '2.1.4',
                question: 'Eisprung und fruchtbare Tage erkennen (inkl. Zyklusbeobachtung)',
                answer: 'Du kannst deinen Zyklus beobachten, Temperatur messen oder Ovulationstests nutzen. So findest du die fruchtbaren Tage heraus.',
                categoryId: '2.1',
              ),
            ],
          ),
          ContentCategory(
            id: '2.2',
            title: 'Körperlich & mental vorbereiten',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.2.1',
                question: 'Wie bereite ich meinen Körper auf eine Schwangerschaft vor?',
                answer: 'Ernähre dich gesund, bewege dich regelmäßig und nimm Folsäure. Auch Arztbesuche zur Kontrolle sind sinnvoll.',
                categoryId: '2.2',
              ),
              ContentQuestion(
                id: '2.2.2',
                question: 'Was unterstützt – und was hemmt – meine Fruchtbarkeit?',
                answer: 'Gut sind: gesunde Ernährung, wenig Stress, kein Rauchen. Schlecht wirken sich Alkohol, Übergewicht oder Schlafmangel aus.',
                categoryId: '2.2',
              ),
              ContentQuestion(
                id: '2.2.3',
                question: 'Wie wichtig ist psychische Gesundheit bei Kinderwunsch?',
                answer: 'Sehr wichtig. Stress kann den Hormonhaushalt stören. Entspannung, Gespräche und Unterstützung helfen.',
                categoryId: '2.2',
              ),
              ContentQuestion(
                id: '2.2.4',
                question: 'Gibt es natürliche Wege zur Fruchtbarkeitssteigerung?',
                answer: 'Ja, z. B. pflanzliche Mittel, Akupunktur oder bestimmte Tees. Wichtig ist, vorher mit einem Arzt darüber zu sprechen.',
                categoryId: '2.2',
              ),
            ],
          ),
          ContentCategory(
            id: '2.3',
            title: 'Medizinische Abklärung & Hilfe',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.3.1',
                question: 'Welche Untersuchungen sind vor einer Schwangerschaft sinnvoll?',
                answer: 'Ein Blutbild, Hormonstatus, Impfstatus und Kontrolle auf Infektionen sind hilfreich, um gut vorbereitet zu sein.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.2',
                question: 'Was tun bei unerfülltem Kinderwunsch?',
                answer: 'Nach einem Jahr ohne Erfolg solltest du dich beim Frauenarzt oder in einer Kinderwunschklinik beraten lassen.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.3',
                question: 'Wann was tun? Künstliche Befruchtung – welche Methoden gibt es?',
                answer: 'Es gibt Insemination, IVF und ICSI. Welche Methode passt, hängt von der Ursache des unerfüllten Kinderwunschs ab.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.4',
                question: 'Was ist eine Kinderwunschklinik?',
                answer: 'Das ist eine spezialisierte Praxis, die Paare mit unerfülltem Kinderwunsch betreut und moderne Behandlungen anbietet.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.5',
                question: 'Was kann der Partner medizinisch beitragen?',
                answer: 'Ein Spermiogramm zeigt, wie es um die Spermien steht. Auch eine Hormon- oder Blutuntersuchung kann sinnvoll sein.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.6',
                question: 'Was tun bei wiederholten Fehlgeburten?',
                answer: 'Ein Arzt kann Ursachen wie Gerinnungsstörungen oder Hormonprobleme untersuchen und gezielt behandeln.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.7',
                question: 'Kann ich trotz Krankheit oder chronischer Erkrankung schwanger werden?',
                answer: 'Oft ja – aber wichtig ist eine gute Betreuung durch Ärzte, damit Mutter und Kind gesund bleiben.',
                categoryId: '2.3',
              ),
            ],
          ),
          ContentCategory(
            id: '2.4',
            title: 'Persönliche und partnerschaftliche Überlegungen',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.4.1',
                question: 'Wann ist der richtige Zeitpunkt für ein Kind?',
                answer: 'Den perfekten Moment gibt es selten. Wenn du dich körperlich und emotional bereit fühlst, ist meist der richtige Zeitpunkt.',
                categoryId: '2.4',
              ),
              ContentQuestion(
                id: '2.4.2',
                question: 'Wie kann ich mich emotional auf ein Kind vorbereiten?',
                answer: 'Sprecht über eure Wünsche und Ängste, informiert euch und lasst euch Zeit. Auch Austausch mit anderen hilft.',
                categoryId: '2.4',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter3',
        title: 'Schwangerschaft',
        imageUrl: 'assets/icons/chapter3.png',
        categories: [
          ContentCategory(
            id: '3.1',
            title: 'Grundlagen der Schwangerschaft',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.1.1',
                question: 'Was ist eine Schwangerschaft und wie entsteht sie?',
                answer: 'Eine Schwangerschaft beginnt, wenn sich eine Eizelle mit einer Samenzelle verbindet und sich in der Gebärmutter einnistet.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.2',
                question: 'Was ist ein Embryo und was ist ein Fötus?',
                answer: 'In den ersten Wochen nennt man das Baby Embryo. Ab der 9. Woche heißt es Fötus – dann sind schon viele Organe angelegt.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.3',
                question: 'Wie lange dauert eine Schwangerschaft?',
                answer: 'Eine Schwangerschaft dauert etwa 40 Wochen oder 9 Monate – gezählt ab dem ersten Tag der letzten Regel.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.4',
                question: 'Was ist ein Trimenon (Trimester)?',
                answer: 'Eine Schwangerschaft wird in drei Teile eingeteilt – jedes Trimester dauert etwa drei Monate und hat typische Veränderungen.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.5',
                question: 'Wie entwickelt sich das Baby Woche für Woche?',
                answer: 'In jeder Woche wächst das Baby weiter – erst bilden sich Organe, dann Arme, Beine, Herz, Gehirn und zum Schluss nimmt es Gewicht zu.',
                categoryId: '3.1',
              ),
            ],
          ),
          ContentCategory(
            id: '3.2',
            title: 'Erste Anzeichen & Bestätigung',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.2.1',
                question: 'Wie merke ich, dass ich schwanger bin?',
                answer: 'Typische Anzeichen sind: ausbleibende Periode, Übelkeit, Brustspannen, Müdigkeit oder ein verändertes Gefühl im Körper.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.2',
                question: 'Wie mache ich einen Schwangerschaftstest?',
                answer: 'Du kannst in der Apotheke einen Test kaufen. Du machst ihn mit Urin, am besten morgens. Zeigt er positiv an, bist du wahrscheinlich schwanger.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.3',
                question: 'Was bedeutet ein positiver Schwangerschaftstest?',
                answer: 'Ein positiver Test zeigt an, dass du sehr wahrscheinlich schwanger bist. Sicherheit bringt ein Besuch beim Frauenarzt.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.4',
                question: 'Was mache ich nach einem positiven Test?',
                answer: 'Vereinbare einen Termin beim Frauenarzt. Dort wird die Schwangerschaft bestätigt und alles Weitere besprochen.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.5',
                question: 'Wann sieht man das Baby im Ultraschall?',
                answer: 'Etwa ab der 6. Woche kann man im Ultraschall etwas sehen – wie eine kleine Fruchthöhle oder schon den Herzschlag.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.6',
                question: 'Was ist das hCG-Hormon?',
                answer: 'hCG ist das Schwangerschaftshormon. Es steigt in den ersten Wochen stark an und sorgt dafür, dass die Schwangerschaft bestehen bleibt.',
                categoryId: '3.2',
              ),
            ],
          ),
          ContentCategory(
            id: '3.3',
            title: 'Körperliche Veränderungen & Gesundheit',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.3.1',
                question: 'Welche körperlichen Veränderungen spüre ich am Anfang?',
                answer: 'Viele Frauen fühlen sich müde, haben empfindliche Brüste, leichte Übelkeit oder ziehen im Unterbauch. Jeder Körper reagiert anders.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.2',
                question: 'Ist Übelkeit in der Frühschwangerschaft normal?',
                answer: 'Ja, das ist sehr häufig. Sie kommt meist durch Hormone und ist oft morgens stärker. Sie geht meist nach dem 3. Monat vorbei.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.3',
                question: 'Was darf ich essen – und was nicht?',
                answer: 'Gesund essen ist wichtig. Vermeide rohes Fleisch, rohen Fisch, Alkohol und bestimmte Käsesorten. Dein Arzt gibt dir eine Liste.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.4',
                question: 'Ist Sport in der Schwangerschaft erlaubt?',
                answer: 'Ja, Bewegung ist gut – z. B. Spazierengehen, Schwimmen oder Yoga. Frag aber deinen Arzt, ob es in deinem Fall okay ist.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.5',
                question: 'Kann ich weiter arbeiten, wenn ich schwanger bin?',
                answer: 'In den meisten Fällen ja – wenn keine Gefahr besteht. Dein Arzt und Arbeitgeber helfen dir dabei, den Arbeitsplatz anzupassen.',
                categoryId: '3.3',
              ),
            ],
          ),
          ContentCategory(
            id: '3.4',
            title: 'Dokumentation & soziale Aspekte',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.4.1',
                question: 'Wann sage ich meiner Familie oder im Job, dass ich schwanger bin?',
                answer: 'Das entscheidest du selbst. Viele warten bis zur 12. Woche. Im Job solltest du es mitteilen, wenn du Schutz brauchst.',
                categoryId: '3.4',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter4',
        title: 'Betreuung in der Schwangerschaft',
        imageUrl: 'assets/icons/chapter4.png',
        categories: [
          ContentCategory(
            id: '4.1',
            title: 'Betreuungspersonen & Rollen',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.1.1',
                question: 'Wer betreut mich während der Schwangerschaft?',
                answer: 'Meist ist es dein Frauenarzt oder deine Frauenärztin, manchmal auch eine Hebamme. Beide arbeiten oft Hand in Hand.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.2',
                question: 'Was macht der Frauenarzt – was die Hebamme?',
                answer: 'Der Arzt macht medizinische Untersuchungen, die Hebamme berät dich, begleitet dich emotional und oft auch bei der Geburt.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.3',
                question: 'Was ist eine Beleghebamme?',
                answer: 'Das ist eine Hebamme, die dich vor, während und nach der Geburt betreut – auch im Krankenhaus, das ihr gemeinsam auswählt.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.4',
                question: 'Was ist eine Doula?',
                answer: 'Eine Doula ist eine erfahrene Frau, die dich zusätzlich emotional unterstützt – sie ersetzt aber keine Hebamme oder Arzt.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.5',
                question: 'Wie finde ich eine Hebamme?',
                answer: 'Frage früh bei deiner Krankenkasse, im Internet oder bei Freunden. Viele Hebammen sind schnell ausgebucht.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.6',
                question: 'Wer begleitet mich zur Geburt?',
                answer: 'Du kannst entscheiden, wer bei dir sein soll – Partner, Freundin, Hebamme oder Doula. Wichtig ist, dass du dich wohlfühlst.',
                categoryId: '4.1',
              ),
            ],
          ),
          ContentCategory(
            id: '4.2',
            title: 'Vorsorge & Diagnostik',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.2.1',
                question: 'Was sind Vorsorgeuntersuchungen – wann und wie oft?',
                answer: 'Sie finden alle 4 Wochen statt, später öfter. Es wird dein Bauch, Urin, Blutdruck und das Baby per Ultraschall kontrolliert.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.2',
                question: 'Welche Ultraschalluntersuchungen gibt es?',
                answer: 'Es gibt drei Standard-Ultraschalle in der Schwangerschaft. Zusätzlich kannst du 3D oder 4D Ultraschall privat machen lassen.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.3',
                question: 'Was wird im Mutterpass dokumentiert?',
                answer: 'Der Mutterpass enthält wichtige Infos zu dir, dem Baby, Untersuchungen und Risiken – er begleitet dich die ganze Schwangerschaft.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.4',
                question: 'Warum wird Blutgruppe und Rhesusfaktor bestimmt?',
                answer: 'Das ist wichtig, falls es Blutungen gibt oder bei der Geburt. Bei bestimmten Kombinationen braucht man eine spezielle Spritze.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.5',
                question: 'Was ist ein Toxoplasmose-Test?',
                answer: 'Der Test zeigt, ob du eine Infektion hast, die dem Baby schaden kann. Er ist nicht immer kostenlos, aber oft sinnvoll.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.6',
                question: 'Was ist ein Röteln- bzw. Toxoplasmose-Titer?',
                answer: 'Das ist ein Blutwert, der zeigt, ob du gegen Röteln oder Toxoplasmose geschützt bist – wichtig für die Gesundheit des Babys.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.7',
                question: 'Welche Blutwerte sind wichtig?',
                answer: 'Zum Beispiel Eisen, Blutzucker, Schilddrüse und bestimmte Antikörper – sie zeigen, ob dein Körper gut für die Schwangerschaft arbeitet.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.8',
                question: 'Welche Tests werden auf Wunsch angeboten?',
                answer: 'Zusatztests wie Nackenfaltenmessung oder Bluttests auf genetische Besonderheiten kannst du freiwillig machen – oft kostenpflichtig.',
                categoryId: '4.2',
              ),
            ],
          ),
          ContentCategory(
            id: '4.3',
            title: 'Medizinische Überwachung & spezielle Tests',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.3.1',
                question: 'Was ist Schwangerschaftsbluthochdruck und wie wird er überwacht?',
                answer: 'Das ist zu hoher Blutdruck in der Schwangerschaft. Er wird bei jeder Kontrolle gemessen, weil er gefährlich sein kann.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.2',
                question: 'Was ist der Glukosetoleranztest (Zuckerbelastungstest)?',
                answer: 'Er zeigt, ob du Schwangerschaftsdiabetes hast. Du trinkst eine Zuckerlösung, danach wird dein Blutzucker kontrolliert.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.3',
                question: 'Was ist Gestationsdiabetes und wie wird er überwacht?',
                answer: 'Das ist ein Diabetes, der in der Schwangerschaft entsteht. Er wird mit Ernährung, Bewegung und manchmal Insulin behandelt.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.4',
                question: 'Wie funktioniert ein CTG (Kardiotokographie)?',
                answer: 'Ein CTG misst die Herztöne des Babys und deine Wehen. Es wird gegen Ende der Schwangerschaft regelmäßig gemacht.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.5',
                question: 'Was ist ein Organscreening?',
                answer: 'Beim Organscreening schaut der Arzt ganz genau per Ultraschall, ob alle Organe des Babys gesund angelegt sind.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.6',
                question: 'Was bringt ein 3D/4D-Ultraschall?',
                answer: 'Er zeigt das Baby in räumlicher Darstellung. Manchmal erkennt man Besonderheiten besser – oft ist es aber nur ein schönes Extra.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.7',
                question: 'Was ist eine Risikoschwangerschaft – was bedeutet das für mich?',
                answer: 'Das heißt, dass du oder dein Baby besonders beobachtet werden – z. B. wegen Alter, Krankheit oder früheren Problemen. Du bekommst mehr Betreuung.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.8',
                question: 'Wie funktioniert die Betreuung bei Komplikationen?',
                answer: 'Du wirst dann engmaschig überwacht – z. B. öftere Untersuchungen oder Krankenhausaufenthalt, damit du und das Baby gesund bleibt.',
                categoryId: '4.3',
              ),
            ],
          ),
          ContentCategory(
            id: '4.4',
            title: 'Geburtsvorbereitung & Organisation',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.4.1',
                question: 'Wann sollte ich mich für eine Klinik entscheiden?',
                answer: 'Am besten bis zur 20. Woche – viele Kliniken sind früh voll. Dann kannst du dich dort auch schon zur Geburt anmelden.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.2',
                question: 'Wie funktioniert die Anmeldung zur Geburt im Krankenhaus?',
                answer: 'Du meldest dich telefonisch oder online an. Manche Kliniken laden zu einem Infoabend ein oder machen ein Gespräch vor Ort.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.3',
                question: 'Was ist bei einer Mehrlingsschwangerschaft besonders?',
                answer: 'Du wirst häufiger untersucht, weil Zwillinge oder mehr Babys ein höheres Risiko haben. Die Geburt wird oft genauer geplant.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.4',
                question: 'Was umfasst die Abschlussuntersuchung kurz vor der Geburt?',
                answer: 'Der Arzt prüft Lage und Gewicht des Babys, Wehen, Muttermund und ob alles bereit für die Geburt ist.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.5',
                question: 'Was ist der Unterschied zwischen ambulanter und stationärer Betreuung?',
                answer: 'Ambulant heißt: du gehst nach der Geburt bald nach Hause. Stationär bedeutet: du bleibst noch einige Tage im Krankenhaus.',
                categoryId: '4.4',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter5',
        title: 'Vorbereitung auf die Geburt',
        imageUrl: 'assets/icons/chapter5.png',
        categories: [
          ContentCategory(
            id: '5.1',
            title: 'Einstieg in die Geburtsvorbereitung',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.1.1',
                question: 'Wann beginne ich mit der Geburtsvorbereitung?',
                answer: 'Am besten ab der 25. Schwangerschaftswoche. So hast du genug Zeit, dich körperlich und mental vorzubereiten.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.2',
                question: 'Was ist ein Geburtsvorbereitungskurs?',
                answer: 'In diesem Kurs lernst du, was bei der Geburt passiert, wie du dich entspannst und wie dein Partner dich unterstützen kann.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.3',
                question: 'Was lerne ich dort?',
                answer: 'Du lernst Atemtechniken, Geburtspositionen, Infos zur Geburt, Wochenbett und wie du mit Schmerzen umgehen kannst.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.4',
                question: 'Braucht auch der Partner eine Vorbereitung?',
                answer: 'Ja, auch Partner können viel lernen – wie sie helfen, unterstützen und bei der Geburt da sein können.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.5',
                question: 'Welche Rolle spielt die Hebamme vor der Geburt?',
                answer: 'Sie begleitet dich, beantwortet Fragen, bereitet dich auf die Geburt vor und hilft, Ängste abzubauen.',
                categoryId: '5.1',
              ),
            ],
          ),
          ContentCategory(
            id: '5.2',
            title: 'Praktisches & Organisation',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.2.1',
                question: 'Was gehört in die Kliniktasche und wann packe ich sie?',
                answer: 'Pack sie etwa 4 Wochen vor dem Geburtstermin. Rein gehören: Kleidung, Hygieneartikel, Unterlagen, Snacks, Baby-Erstausstattung.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.3',
                question: 'Was ist ein Geburtsplan – und wie schreibe ich ihn?',
                answer: 'Im Plan notierst du Wünsche zur Geburt: z. B. Schmerzmittel, Positionen, wer dabei sein soll. Es ist eine Hilfe für das Klinikteam.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.4',
                question: 'Was ist wichtig für die Wahl des Geburtsortes?',
                answer: 'Wichtig sind Nähe, Ausstattung, Umgang mit Notfällen und dein Bauchgefühl. Klinik, Geburtshaus oder Zuhause – alles ist möglich.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.5',
                question: 'Geburt im Krankenhaus, Geburtshaus oder zu Hause – was passt zu mir?',
                answer: 'Das hängt von deiner Gesundheit, deinen Wünschen und deiner Sicherheit ab. Sprich mit Arzt oder Hebamme darüber.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.6',
                question: 'Was ist ein Risiko bei einer Hausgeburt?',
                answer: 'Es gibt weniger medizinische Geräte als im Krankenhaus. Bei Komplikationen muss man schnell dorthin wechseln können.',
                categoryId: '5.2',
              ),
            ],
          ),
          ContentCategory(
            id: '5.3',
            title: 'Mentale & körperliche Vorbereitung',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.3.1',
                question: 'Wie bereite ich mich mental auf die Geburt vor?',
                answer: 'Spreche über Ängste, informiere dich, übe Entspannung und vertraue deinem Körper. Auch Kurse und Gespräche helfen.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.2',
                question: 'Was kann ich tun gegen Ängste vor der Geburt?',
                answer: 'Rede mit deiner Hebamme, lerne Entspannungstechniken und sprich mit anderen Müttern über ihre Erfahrungen.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.3',
                question: 'Welche Entspannungsmethoden helfen?',
                answer: 'Atemübungen, Meditation, Massagen, ruhige Musik und Bewegung können dir helfen, ruhig und gelassen zu bleiben.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.4',
                question: 'Welche Zeichen deuten auf den baldigen Geburtsbeginn hin?',
                answer: 'Zeichen sind: regelmäßige Wehen, Blasensprung, Schleimpfropfabgang oder Rückenschmerzen. Dann kann es bald losgehen.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.5',
                question: 'Was ist der Nestbautrieb?',
                answer: 'Kurz vor der Geburt verspüren viele Frauen den Wunsch, alles aufzuräumen und vorzubereiten – das ist ganz normal.',
                categoryId: '5.3',
              ),
            ],
          ),
          ContentCategory(
            id: '5.4',
            title: 'Körperliche Vorbereitung & Übungen',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.4.1',
                question: 'Welche Rolle spielt Bewegung in der späten Schwangerschaft?',
                answer: 'Sie stärkt deinen Körper, fördert die Durchblutung und kann helfen, besser zu schlafen und dich auf die Geburt vorzubereiten.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.2',
                question: 'Welche Übungen bereiten auf die Geburt vor?',
                answer: 'Gut sind: Beckenbodenübungen, Atemtechniken, leichte Yoga- oder Dehnübungen. Deine Hebamme zeigt dir, was passt.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.3',
                question: 'Welche Geburtspositionen kann ich üben?',
                answer: 'Zum Beispiel: Vierfüßlerstand, Hocken, Stehen, Liegen. Probiere aus, was sich gut anfühlt – dein Körper zeigt dir den Weg.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.4',
                question: 'Wie kann ich meine Beckenbodenmuskulatur vorbereiten?',
                answer: 'Mit speziellen Übungen trainierst du die Muskeln im Becken – sie helfen bei der Geburt und beugen späterem Harnverlust vor.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.5',
                question: 'Was ist eine Dammmassage und wozu dient sie?',
                answer: 'Sie macht das Gewebe dehnbarer und kann helfen, einen Dammriss bei der Geburt zu vermeiden. Du kannst sie ab Woche 34 machen.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.6',
                question: 'Was passiert bei der geburtsvorbereitenden Akupunktur?',
                answer: 'Feine Nadeln werden an bestimmten Punkten gesetzt. Das soll den Körper auf die Geburt vorbereiten und Schmerzen lindern.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.7',
                question: 'Was ist ein CTG und wann wird es gemacht?',
                answer: 'Ein CTG misst die Herztöne des Babys und deine Wehen. Es wird meist ab der 30. Woche regelmäßig gemacht.',
                categoryId: '5.4',
              ),
            ],
          ),
          ContentCategory(
            id: '5.5',
            title: 'Besondere Vorbereitungssituationen',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.5.1',
                question: 'Was ist bei Mehrlingsschwangerschaften anders in der Vorbereitung?',
                answer: 'Die Geburt wird genauer geplant, es gibt mehr Kontrollen und oft ist ein Kaiserschnitt nötig – deine Klinik hilft dir dabei.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.2',
                question: 'Wie kann ich mich auf eine Frühgeburt vorbereiten?',
                answer: 'Besprich alles mit Arzt und Klinik. Wichtig sind Ruhe, engmaschige Kontrolle und Informationen zu Frühchenversorgung.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.3',
                question: 'Was ist, wenn das Baby in Beckenendlage liegt?',
                answer: 'Manchmal kann sich das Baby noch drehen. Es gibt spezielle Übungen oder eine äußere Wendung durch den Arzt.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.4',
                question: 'Wie bereite ich mich bei geplanter Sectio (Kaiserschnitt) vor?',
                answer: 'Du wirst gut aufgeklärt. Die Klinik erklärt dir alles und du bekommst meist vorab einen Termin für die OP.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.5',
                question: 'Wer hilft mir bei der Vorbereitung, wenn ich alleine bin?',
                answer: 'Hebammen, Beratungsstellen oder Freunde können dich unterstützen. Du bist nicht allein – es gibt Hilfe für dich.',
                categoryId: '5.5',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter6',
        title: 'Die Geburt – was dich erwartet',
        imageUrl: 'assets/icons/chapter6.png',
        categories: [
          ContentCategory(
            id: '6.1',
            title: 'Ankunft & Aufnahme',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.1.1',
                question: 'Wann sollte ich ins Krankenhaus oder Geburtshaus fahren?',
                answer: 'Wenn die Wehen regelmäßig kommen, die Fruchtblase platzt oder du Schmerzen hast, solltest du dich auf den Weg machen.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.2',
                question: 'Was passiert bei der Aufnahme zur Geburt?',
                answer: 'Du wirst untersucht, gefragt wie es dir geht, ein CTG gemacht und geschaut, wie weit die Geburt schon ist.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.3',
                question: 'Welche Untersuchungen werden zu Beginn gemacht?',
                answer: 'Meist ein CTG, Abtasten des Bauches, vaginaler Befund und manchmal eine Ultraschalluntersuchung.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.4',
                question: 'Was ist der Muttermund und wie wird er kontrolliert?',
                answer: 'Der Muttermund ist der Ausgang der Gebärmutter. Er wird bei einer vaginalen Untersuchung auf seine Öffnung geprüft.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.5',
                question: 'Was ist ein CTG und warum ist es wichtig?',
                answer: 'Ein CTG misst die Herztöne deines Babys und deine Wehen. So sieht man, wie es dem Baby geht.',
                categoryId: '6.1',
              ),
            ],
          ),
          ContentCategory(
            id: '6.2',
            title: 'Schmerzlinderung & Geburtsmethoden',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.2.1',
                question: 'Welche Schmerzmittel stehen während der Geburt zur Verfügung?',
                answer: 'Es gibt viele Möglichkeiten: Atemtechniken, Wärme, Massage, Schmerzmittel, Lachgas oder eine PDA.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.2',
                question: 'Was ist eine PDA (Periduralanästhesie)?',
                answer: 'Eine PDA ist eine Spritze in den Rücken, die den Unterleib betäubt – so spürst du die Wehen kaum noch.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.3',
                question: 'Was ist eine Spinalanästhesie?',
                answer: 'Sie wirkt schneller als die PDA und wird oft bei geplanten Kaiserschnitten eingesetzt.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.4',
                question: 'Was ist eine Wassergeburt und wie läuft sie ab?',
                answer: 'Du gebärst in einer speziellen Wanne. Das warme Wasser entspannt und kann Schmerzen lindern.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.5',
                question: 'Welche natürlichen Methoden zur Schmerzlinderung gibt es?',
                answer: 'Bewegung, Atemtechniken, Massage, Wasser, Gebärhocker oder Partnerhilfe – alles kann dir helfen.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.6',
                question: 'Was ist, wenn ich Angst vor der Geburt habe?',
                answer: 'Rede darüber mit deiner Hebamme. Es gibt Geburtsvorbereitung, Hypnobirthing und Unterstützung für dich.',
                categoryId: '6.2',
              ),
            ],
          ),
          ContentCategory(
            id: '6.3',
            title: 'Ablauf der vaginalen Geburt',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.3.1',
                question: 'Wie läuft eine vaginale Geburt ab – Schritt für Schritt?',
                answer: 'Erst öffnen sich Muttermund und Gebärmutter. Dann kommt die Pressphase und schließlich wird das Baby geboren.',
                categoryId: '6.3',
              ),
              ContentQuestion(
                id: '6.3.2',
                question: 'Welche Positionen kann ich während der Geburt einnehmen?',
                answer: 'Stehend, sitzend, kniend, liegend – du kannst wählen, was für dich am angenehmsten ist.',
                categoryId: '6.3',
              ),
              ContentQuestion(
                id: '6.3.3',
                question: 'Was passiert beim Pressen?',
                answer: 'Du hilfst aktiv mit, das Baby nach draußen zu schieben – dabei wirst du von Hebamme oder Arzt angeleitet.',
                categoryId: '6.3',
              ),
              ContentQuestion(
                id: '6.3.4',
                question: 'Was passiert direkt nach der Geburt des Babys?',
                answer: 'Das Baby kommt auf deinen Bauch, die Nabelschnur wird durchtrennt und du bekommst meist die Plazenta.',
                categoryId: '6.3',
              ),
            ],
          ),
          ContentCategory(
            id: '6.4',
            title: 'Körperliche Folgen & Versorgung',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.4.1',
                question: 'Was ist ein Dammschnitt und wann wird er gemacht?',
                answer: 'Ein Dammschnitt ist ein kleiner Schnitt am Scheidenausgang – er wird nur gemacht, wenn es nötig ist, z. B. bei Gefahr fürs Baby.',
                categoryId: '6.4',
              ),
              ContentQuestion(
                id: '6.4.2',
                question: 'Was ist ein Dammriss?',
                answer: 'Der Damm kann bei der Geburt reißen – das heilt meist gut und wird vom Arzt direkt genäht.',
                categoryId: '6.4',
              ),
              ContentQuestion(
                id: '6.4.3',
                question: 'Wie wird ein Dammriss versorgt?',
                answer: 'Der Riss wird nach der Geburt mit Faden genäht, der sich später selbst auflöst. Schmerzmittel helfen beim Heilen.',
                categoryId: '6.4',
              ),
              ContentQuestion(
                id: '6.4.4',
                question: 'Was passiert mit der Plazenta nach der Geburt?',
                answer: 'Sie wird meist kurz nach dem Baby geboren – das nennt man Nachgeburt. Der Arzt prüft, ob sie vollständig ist.',
                categoryId: '6.4',
              ),
            ],
          ),
          ContentCategory(
            id: '6.5',
            title: 'Baby & erstes Bonding',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.5.1',
                question: 'Was ist das Bonding nach der Geburt?',
                answer: 'Bonding ist das erste Kuscheln mit deinem Baby – es stärkt eure Verbindung und gibt Sicherheit und Wärme.',
                categoryId: '6.5',
              ),
              ContentQuestion(
                id: '6.5.2',
                question: 'Wie wird das Baby nach der Geburt untersucht?',
                answer: 'Der Arzt prüft Atmung, Herzschlag, Reflexe und Aussehen – alles schnell und liebevoll.',
                categoryId: '6.5',
              ),
              ContentQuestion(
                id: '6.5.3',
                question: 'Was ist das APGAR-Schema?',
                answer: 'Es bewertet Atmung, Puls, Muskelspannung, Aussehen und Reflexe – direkt nach der Geburt, nach 5 und 10 Minuten.',
                categoryId: '6.5',
              ),
            ],
          ),
          ContentCategory(
            id: '6.6',
            title: 'Besonderheiten & Komplikationen',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.6.1',
                question: 'Welche Rolle spielt die Hebamme während der Geburt?',
                answer: 'Sie ist die wichtigste Begleiterin, unterstützt dich bei den Wehen, beobachtet dich und das Baby und hilft bei Entscheidungen.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.2',
                question: 'Was ist ein Geburtsstillstand?',
                answer: 'Wenn sich der Muttermund nicht weiter öffnet oder das Baby nicht tiefer rutscht, spricht man von einem Stillstand – dann wird gehandelt.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.3',
                question: 'Was passiert bei einer Saugglocken-Geburt?',
                answer: 'Eine kleine Glocke wird am Babykopf angesetzt, um beim letzten Stück Geburt zu helfen – das ist meist harmlos für das Kind.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.4',
                question: 'Wann wird eine Zangengeburt notwendig?',
                answer: 'Wenn es dem Baby schlecht geht oder es schnell gehen muss, kann eine Zange helfen, es sanft herauszuziehen.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.5',
                question: 'Wann und wie wird ein Kaiserschnitt durchgeführt?',
                answer: 'Wenn eine normale Geburt nicht möglich ist oder ein Risiko besteht. Dabei wird das Baby über einen Bauchschnitt geholt.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.6',
                question: 'Was ist der Unterschied zwischen geplantem und Notkaiserschnitt?',
                answer: 'Ein geplanter Kaiserschnitt findet vor Wehenbeginn statt. Ein Notkaiserschnitt passiert, wenn bei der Geburt Komplikationen auftreten.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.7',
                question: 'Was bedeutet eine Sturzgeburt?',
                answer: 'Das ist eine sehr schnelle Geburt, bei der alles plötzlich passiert – sie ist selten, aber meist nicht gefährlich.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.8',
                question: 'Was ist eine ambulante Geburt?',
                answer: 'Du bleibst nur wenige Stunden nach der Geburt im Krankenhaus und gehst dann nach Hause – mit Hebammenbegleitung.',
                categoryId: '6.6',
              ),
            ],
          ),
        ],
      ),
    ]);
  }
}