import '../models/content_model.dart';

class SampleDataFR {
  static ContentData getSampleContent() {
    return ContentData(sections: [
      ContentSection(
        id: 'chapter1',
        title: 'Ma première visite chez le gynécologue',
        imageUrl: '/assets/icons/chapter1.png',
        categories: [
          ContentCategory(
            id: '1.1',
            title: 'Introduction à la gynécologie',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.1.1',
                question: 'Que fait un gynécologue ?',
                answer: 'Un gynécologue s\'occupe de la santé des femmes - particulièrement des sujets liés aux règles, à la grossesse, à l\'accouchement et à la ménopause.',
                categoryId: '1.1',
              ),
              ContentQuestion(
                id: '1.1.2',
                question: 'Comment trouver un gynécologue adapté ?',
                answer: 'Vous pouvez consulter les avis en ligne ou demander à des amis et à la famille. L\'important est que vous vous sentiez à l\'aise et comprise.',
                categoryId: '1.1',
              ),
              ContentQuestion(
                id: '1.1.3',
                question: 'Qu\'est-ce qu\'une consultation gynécologique ?',
                answer: 'C\'est une discussion ou un examen chez le gynécologue. Il s\'agit de votre santé, de questions sur la contraception, les règles ou la grossesse.',
                categoryId: '1.1',
              ),
            ],
          ),
          ContentCategory(
            id: '1.2',
            title: 'Premières étapes en cas de suspicion de grossesse',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.2.1',
                question: 'Que se passe-t-il lors de la première consultation ?',
                answer: 'Le médecin pose des questions, fait peut-être une échographie ou prélève du sang pour voir si vous êtes enceinte et comment vous allez.',
                categoryId: '1.2',
              ),
              ContentQuestion(
                id: '1.2.2',
                question: 'Comment me préparer à un examen gynécologique ?',
                answer: 'Vous n\'avez pas besoin de faire quoi que ce soit de spécial - juste être propre. Vous pouvez prendre une douche avant, mais pas besoin de vous raser ou autre.',
                categoryId: '1.2',
              ),
              ContentQuestion(
                id: '1.2.3',
                question: 'Quels termes devrais-je connaître ?',
                answer: 'Les termes importants sont : cycle (menstruation), ovulation, échographie, utérus et hormone. Votre médecin vous expliquera tout en détail.',
                categoryId: '1.2',
              ),
              ContentQuestion(
                id: '1.2.4',
                question: 'Que ne dois-je pas oublier ?',
                answer: 'Apportez votre pièce d\'identité, votre carte d\'assurance maladie et les questions que vous souhaitez poser. Notez tout ce qui est important pour vous.',
                categoryId: '1.2',
              ),
            ],
          ),
          ContentCategory(
            id: '1.3',
            title: 'Bases du corps féminin',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.3.1',
                question: 'Que signifie le cycle ?',
                answer: 'Le cycle est la période entre une menstruation et la suivante. Il montre que votre corps est prêt à être enceinte.',
                categoryId: '1.3',
              ),
              ContentQuestion(
                id: '1.3.2',
                question: 'Quel rôle joue l\'utérus ?',
                answer: 'L\'utérus est l\'endroit où le bébé grandit. Il protège et nourrit le bébé pendant la grossesse.',
                categoryId: '1.3',
              ),
              ContentQuestion(
                id: '1.3.3',
                question: 'Que sont les hormones et pourquoi sont-elles importantes ?',
                answer: 'Les hormones sont des messagers dans votre corps. Elles contrôlent vos règles, votre ovulation et aussi la grossesse.',
                categoryId: '1.3',
              ),
              ContentQuestion(
                id: '1.3.4',
                question: 'Qu\'est-ce que l\'acide folique et pourquoi en a-t-on besoin ?',
                answer: 'L\'acide folique est une vitamine. Elle aide le bébé à se développer sainement - surtout pendant les premières semaines de grossesse.',
                categoryId: '1.3',
              ),
            ],
          ),
          ContentCategory(
            id: '1.4',
            title: 'Suivi pendant la grossesse',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.4.2',
                question: 'Quand dois-je aller à l\'hôpital - et pourquoi ?',
                answer: 'Si vous avez de fortes douleurs, des saignements ou ne sentez plus votre bébé bouger. Vous allez aussi à l\'hôpital pour l\'accouchement.',
                categoryId: '1.4',
              ),
              ContentQuestion(
                id: '1.4.3',
                question: 'Qui peut m\'accompagner pendant la grossesse ?',
                answer: 'Vous pouvez décider qui est avec vous - votre partenaire, une amie ou un membre de votre famille.',
                categoryId: '1.4',
              ),
              ContentQuestion(
                id: '1.4.4',
                question: 'Quelles maladies associées peuvent survenir ?',
                answer: 'Certaines femmes développent du diabète, de l\'hypertension ou des douleurs au dos. Votre médecin surveillera régulièrement votre santé.',
                categoryId: '1.4',
              ),
            ],
          ),
          ContentCategory(
            id: '1.5',
            title: 'Aspects émotionnels et culturels',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.5.1',
                question: 'Soutien psychologique : Comment gérer les incertitudes et les peurs ?',
                answer: 'Parlez à votre médecin ou à un conseiller. C\'est tout à fait normal d\'avoir parfois peur. Vous n\'êtes pas seule.',
                categoryId: '1.5',
              ),
              ContentQuestion(
                id: '1.5.2',
                question: 'Différences culturelles dans le suivi de grossesse',
                answer: 'Différentes cultures ont leurs propres rituels. L\'important est que vous vous sentiez à l\'aise avec les soins - parlez ouvertement avec votre médecin.',
                categoryId: '1.5',
              ),
            ],
          ),
          ContentCategory(
            id: '1.6',
            title: 'Questions pratiques',
            imageUrl: '',
            sectionId: 'chapter1',
            questions: [
              ContentQuestion(
                id: '1.6.1',
                question: 'Combien coûte une grossesse ?',
                answer: 'L\'assurance maladie couvre la plupart des examens. Certains extras comme l\'échographie 3D coûtent en supplément.',
                categoryId: '1.6',
              ),
              ContentQuestion(
                id: '1.6.2',
                question: 'Quels droits ai-je en tant que femme enceinte ?',
                answer: 'Vous avez par exemple droit à la protection de la maternité, aux rendez-vous médicaux pendant les heures de travail et à la protection contre le licenciement.',
                categoryId: '1.6',
              ),
              ContentQuestion(
                id: '1.6.3',
                question: 'Qu\'est-ce que la protection de la maternité ?',
                answer: 'C\'est une pause légale avant et après la naissance. Pendant cette période, vous n\'avez pas à travailler et continuez à recevoir de l\'argent.',
                categoryId: '1.6',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter2',
        title: 'Désir d\'enfant & préparation à la grossesse',
        imageUrl: '/assets/icons/chapter2.png',
        categories: [
          ContentCategory(
            id: '2.1',
            title: 'Bases de la fertilité',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.1.1',
                question: 'Que signifie la fertilité - et de quoi dépend-elle ?',
                answer: 'La fertilité signifie que vous pouvez tomber enceinte. Elle dépend de votre cycle, de votre âge, de votre mode de vie et de votre santé.',
                categoryId: '2.1',
              ),
              ContentQuestion(
                id: '2.1.2',
                question: 'Comment l\'âge affecte-t-il la fertilité ?',
                answer: 'Avec l\'âge, il devient plus difficile de tomber enceinte - surtout à partir de la mi-trentaine. La qualité des ovules diminue.',
                categoryId: '2.1',
              ),
              ContentQuestion(
                id: '2.1.3',
                question: 'Quel rôle joue le partenaire dans la planification familiale ?',
                answer: 'La qualité du sperme est également importante. Un mode de vie sain et des examens aident à évaluer la fertilité du partenaire.',
                categoryId: '2.1',
              ),
              ContentQuestion(
                id: '2.1.4',
                question: 'Reconnaître l\'ovulation et les jours fertiles (y compris le suivi du cycle)',
                answer: 'Vous pouvez observer votre cycle, mesurer la température ou utiliser des tests d\'ovulation. Cela vous aide à découvrir vos jours fertiles.',
                categoryId: '2.1',
              ),
            ],
          ),
          ContentCategory(
            id: '2.2',
            title: 'Préparation physique & mentale',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.2.1',
                question: 'Comment préparer mon corps à une grossesse ?',
                answer: 'Mangez sainement, faites régulièrement de l\'exercice et prenez de l\'acide folique. Les visites régulières chez le médecin pour des contrôles sont également utiles.',
                categoryId: '2.2',
              ),
              ContentQuestion(
                id: '2.2.2',
                question: 'Qu\'est-ce qui favorise - et qu\'est-ce qui entrave - ma fertilité ?',
                answer: 'Bon : alimentation saine, peu de stress, pas de tabac. Mauvais effets : alcool, surpoids ou manque de sommeil.',
                categoryId: '2.2',
              ),
              ContentQuestion(
                id: '2.2.3',
                question: 'Quelle est l\'importance de la santé mentale quand on veut un enfant ?',
                answer: 'Très importante. Le stress peut perturber l\'équilibre hormonal. La relaxation, les conversations et le soutien aident.',
                categoryId: '2.2',
              ),
              ContentQuestion(
                id: '2.2.4',
                question: 'Existe-t-il des moyens naturels d\'augmenter la fertilité ?',
                answer: 'Oui, par exemple, des remèdes à base de plantes, l\'acupuncture ou certaines tisanes. Il est important d\'en discuter avec un médecin au préalable.',
                categoryId: '2.2',
              ),
            ],
          ),
          ContentCategory(
            id: '2.3',
            title: 'Clarification médicale & aide',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.3.1',
                question: 'Quels examens sont judicieux avant une grossesse ?',
                answer: 'Une numération sanguine, un bilan hormonal, un statut vaccinal et un contrôle des infections sont utiles pour être bien préparée.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.2',
                question: 'Que faire en cas de difficultés à concevoir ?',
                answer: 'Après un an sans succès, vous devriez consulter votre gynécologue ou une clinique de fertilité.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.3',
                question: 'Quand faire quoi ? Insémination artificielle - quelles méthodes sont disponibles ?',
                answer: 'Il y a l\'insémination, la FIV et l\'ICSI. La méthode appropriée dépend de la cause de l\'infertilité.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.4',
                question: 'Qu\'est-ce qu\'une clinique de fertilité ?',
                answer: 'C\'est un établissement spécialisé qui accompagne les couples ayant un désir d\'enfant non satisfait et propose des traitements modernes.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.5',
                question: 'Quelle peut être la contribution médicale du partenaire ?',
                answer: 'Un spermogramme montre l\'état des spermatozoïdes. Des tests hormonaux ou sanguins peuvent également être utiles.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.6',
                question: 'Que faire en cas de fausses couches répétées ?',
                answer: 'Un médecin peut rechercher des causes comme des troubles de la coagulation ou des problèmes hormonaux et proposer un traitement ciblé.',
                categoryId: '2.3',
              ),
              ContentQuestion(
                id: '2.3.7',
                question: 'Puis-je tomber enceinte malgré une maladie ou une affection chronique ?',
                answer: 'Souvent oui - mais des soins médicaux adaptés sont importants pour que la mère et l\'enfant restent en bonne santé.',
                categoryId: '2.3',
              ),
            ],
          ),
          ContentCategory(
            id: '2.4',
            title: 'Considérations personnelles et de couple',
            imageUrl: '',
            sectionId: 'chapter2',
            questions: [
              ContentQuestion(
                id: '2.4.1',
                question: 'Quel est le bon moment pour avoir un enfant ?',
                answer: 'Le moment parfait existe rarement. Quand vous vous sentez prête physiquement et émotionnellement, c\'est généralement le bon moment.',
                categoryId: '2.4',
              ),
              ContentQuestion(
                id: '2.4.2',
                question: 'Comment puis-je me préparer émotionnellement à avoir un enfant ?',
                answer: 'Parlez de vos souhaits et de vos peurs, informez-vous et prenez votre temps. Échanger avec d\'autres personnes aide aussi.',
                categoryId: '2.4',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter3',
        title: 'Grossesse',
        imageUrl: '/assets/icons/chapter3.png',
        categories: [
          ContentCategory(
            id: '3.1',
            title: 'Bases de la grossesse',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.1.1',
                question: 'Qu\'est-ce que la grossesse et comment se produit-elle ?',
                answer: 'La grossesse commence lorsqu\'un ovule se combine avec un spermatozoïde et s\'implante dans l\'utérus.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.2',
                question: 'Qu\'est-ce qu\'un embryon et qu\'est-ce qu\'un fœtus ?',
                answer: 'Dans les premières semaines, le bébé est appelé embryon. À partir de la 9e semaine, on parle de fœtus - à ce stade, de nombreux organes sont déjà formés.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.3',
                question: 'Combien de temps dure une grossesse ?',
                answer: 'Une grossesse dure environ 40 semaines ou 9 mois - comptés à partir du premier jour de vos dernières règles.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.4',
                question: 'Qu\'est-ce qu\'un trimestre ?',
                answer: 'La grossesse est divisée en trois parties - chaque trimestre dure environ trois mois et présente des changements typiques.',
                categoryId: '3.1',
              ),
              ContentQuestion(
                id: '3.1.5',
                question: 'Comment le bébé se développe-t-il semaine après semaine ?',
                answer: 'Chaque semaine, le bébé grandit - d\'abord les organes se forment, puis les bras, les jambes, le cœur, le cerveau, et enfin il prend du poids.',
                categoryId: '3.1',
              ),
            ],
          ),
          ContentCategory(
            id: '3.2',
            title: 'Premiers signes & confirmation',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.2.1',
                question: 'Comment savoir si je suis enceinte ?',
                answer: 'Les signes typiques sont : absence de règles, nausées, sensibilité des seins, fatigue ou une sensation différente dans votre corps.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.2',
                question: 'Comment faire un test de grossesse ?',
                answer: 'Vous pouvez acheter un test en pharmacie. Vous le faites avec de l\'urine, de préférence le matin. S\'il est positif, vous êtes probablement enceinte.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.3',
                question: 'Que signifie un test de grossesse positif ?',
                answer: 'Un test positif indique que vous êtes très probablement enceinte. Une visite chez le gynécologue apporte une certitude.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.4',
                question: 'Que faire après un test positif ?',
                answer: 'Prenez rendez-vous avec votre gynécologue. La grossesse y sera confirmée et tout le reste sera discuté.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.5',
                question: 'Quand peut-on voir le bébé à l\'échographie ?',
                answer: 'À partir de la 6e semaine environ, on peut voir quelque chose à l\'échographie - comme un petit sac gestationnel ou déjà les battements du cœur.',
                categoryId: '3.2',
              ),
              ContentQuestion(
                id: '3.2.6',
                question: 'Qu\'est-ce que l\'hormone hCG ?',
                answer: 'L\'hCG est l\'hormone de grossesse. Elle augmente fortement dans les premières semaines et assure le maintien de la grossesse.',
                categoryId: '3.2',
              ),
            ],
          ),
          ContentCategory(
            id: '3.3',
            title: 'Changements physiques & santé',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.3.1',
                question: 'Quels changements physiques ressent-on au début ?',
                answer: 'Beaucoup de femmes se sentent fatiguées, ont les seins sensibles, des nausées légères ou des tiraillements dans le bas-ventre. Chaque corps réagit différemment.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.2',
                question: 'Les nausées en début de grossesse sont-elles normales ?',
                answer: 'Oui, c\'est très courant. Elles viennent généralement des hormones et sont souvent plus fortes le matin. Elles passent généralement après le 3e mois.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.3',
                question: 'Que puis-je manger - et que dois-je éviter ?',
                answer: 'Manger sainement est important. Évitez la viande crue, le poisson cru, l\'alcool et certains fromages. Votre médecin vous donnera une liste.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.4',
                question: 'L\'exercice est-il autorisé pendant la grossesse ?',
                answer: 'Oui, le mouvement est bon - par exemple, la marche, la natation ou le yoga. Mais demandez à votre médecin si c\'est approprié dans votre cas.',
                categoryId: '3.3',
              ),
              ContentQuestion(
                id: '3.3.5',
                question: 'Puis-je continuer à travailler pendant ma grossesse ?',
                answer: 'Dans la plupart des cas oui - s\'il n\'y a pas de danger. Votre médecin et votre employeur vous aideront à adapter votre lieu de travail.',
                categoryId: '3.3',
              ),
            ],
          ),
          ContentCategory(
            id: '3.4',
            title: 'Documentation & aspects sociaux',
            imageUrl: '',
            sectionId: 'chapter3',
            questions: [
              ContentQuestion(
                id: '3.4.1',
                question: 'Quand dois-je annoncer à ma famille ou au travail que je suis enceinte ?',
                answer: 'C\'est votre décision. Beaucoup attendent jusqu\'à la 12e semaine. Au travail, vous devriez le mentionner quand vous avez besoin de protection.',
                categoryId: '3.4',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter4',
        title: 'Suivi pendant la grossesse',
        imageUrl: '/assets/icons/chapter4.png',
        categories: [
          ContentCategory(
            id: '4.1',
            title: 'Soignants & rôles',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.1.1',
                question: 'Qui s\'occupe de moi pendant la grossesse ?',
                answer: 'Habituellement, c\'est votre gynécologue, parfois aussi une sage-femme. Les deux travaillent souvent main dans la main.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.2',
                question: 'Que fait le gynécologue - que fait la sage-femme ?',
                answer: 'Le médecin effectue des examens médicaux, la sage-femme vous conseille, vous accompagne émotionnellement et souvent lors de l\'accouchement.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.3',
                question: 'Qu\'est-ce qu\'une sage-femme libérale ?',
                answer: 'C\'est une sage-femme qui s\'occupe de vous avant, pendant et après la naissance - également à l\'hôpital que vous choisissez ensemble.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.4',
                question: 'Qu\'est-ce qu\'une doula ?',
                answer: 'Une doula est une femme expérimentée qui vous offre un soutien émotionnel supplémentaire - mais elle ne remplace pas une sage-femme ou un médecin.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.5',
                question: 'Comment trouver une sage-femme ?',
                answer: 'Demandez tôt à votre assurance maladie, en ligne ou à des amis. De nombreuses sages-femmes sont rapidement réservées.',
                categoryId: '4.1',
              ),
              ContentQuestion(
                id: '4.1.6',
                question: 'Qui m\'accompagne à l\'accouchement ?',
                answer: 'Vous pouvez décider qui doit être avec vous - partenaire, amie, sage-femme ou doula. L\'important est que vous vous sentiez à l\'aise.',
                categoryId: '4.1',
              ),
            ],
          ),
          ContentCategory(
            id: '4.2',
            title: 'Soins prénataux & diagnostics',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.2.1',
                question: 'Que sont les examens prénataux - quand et à quelle fréquence ?',
                answer: 'Ils ont lieu toutes les 4 semaines, plus souvent par la suite. Votre abdomen, urine, tension artérielle et le bébé sont contrôlés par échographie.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.2',
                question: 'Quels examens échographiques existe-t-il ?',
                answer: 'Il y a trois échographies standard pendant la grossesse. En plus, vous pouvez faire faire des échographies 3D ou 4D en privé.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.3',
                question: 'Qu\'est-ce qui est documenté dans le carnet de maternité ?',
                answer: 'Le carnet de maternité contient des informations importantes sur vous, le bébé, les examens et les risques - il vous accompagne tout au long de la grossesse.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.4',
                question: 'Pourquoi détermine-t-on le groupe sanguin et le facteur Rhésus ?',
                answer: 'C\'est important en cas de saignements ou lors de l\'accouchement. Certaines combinaisons nécessitent une injection spéciale.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.5',
                question: 'Qu\'est-ce qu\'un test de toxoplasmose ?',
                answer: 'Le test montre si vous avez une infection qui pourrait nuire au bébé. Il n\'est pas toujours gratuit, mais souvent utile.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.6',
                question: 'Qu\'est-ce qu\'un titre de rubéole ou de toxoplasmose ?',
                answer: 'C\'est une valeur sanguine qui montre si vous êtes protégée contre la rubéole ou la toxoplasmose - important pour la santé du bébé.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.7',
                question: 'Quelles valeurs sanguines sont importantes ?',
                answer: 'Par exemple, le fer, la glycémie, la thyroïde et certains anticorps - ils montrent si votre corps fonctionne bien pour la grossesse.',
                categoryId: '4.2',
              ),
              ContentQuestion(
                id: '4.2.8',
                question: 'Quels tests sont proposés sur demande ?',
                answer: 'Des tests supplémentaires comme la mesure de la clarté nucale ou des tests sanguins pour les caractéristiques génétiques peuvent être faits volontairement - souvent payants.',
                categoryId: '4.2',
              ),
            ],
          ),
          ContentCategory(
            id: '4.3',
            title: 'Surveillance médicale & tests spéciaux',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.3.1',
                question: 'Qu\'est-ce que l\'hypertension liée à la grossesse et comment est-elle surveillée ?',
                answer: 'C\'est une tension artérielle élevée pendant la grossesse. Elle est mesurée à chaque contrôle car elle peut être dangereuse.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.2',
                question: 'Qu\'est-ce que le test de tolérance au glucose (test de charge en sucre) ?',
                answer: 'Il montre si vous avez un diabète gestationnel. Vous buvez une solution sucrée, puis votre glycémie est vérifiée.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.3',
                question: 'Qu\'est-ce que le diabète gestationnel et comment est-il surveillé ?',
                answer: 'C\'est un diabète qui se développe pendant la grossesse. Il est traité par l\'alimentation, l\'exercice et parfois l\'insuline.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.4',
                question: 'Comment fonctionne un monitoring (cardiotocographie) ?',
                answer: 'Un monitoring mesure les battements du cœur du bébé et vos contractions. Il est régulièrement fait vers la fin de la grossesse.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.5',
                question: 'Qu\'est-ce qu\'un dépistage des organes ?',
                answer: 'Lors du dépistage des organes, le médecin vérifie par échographie si tous les organes du bébé se développent sainement.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.6',
                question: 'Que permet une échographie 3D/4D ?',
                answer: 'Elle montre le bébé en représentation spatiale. Parfois, on peut mieux reconnaître certaines caractéristiques - mais c\'est souvent juste un agréable bonus.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.7',
                question: 'Qu\'est-ce qu\'une grossesse à haut risque - qu\'est-ce que cela signifie pour moi ?',
                answer: 'Cela signifie que vous ou votre bébé nécessitez une observation spéciale - par exemple, en raison de l\'âge, d\'une maladie ou de problèmes antérieurs. Vous recevez plus de soins.',
                categoryId: '4.3',
              ),
              ContentQuestion(
                id: '4.3.8',
                question: 'Comment se déroulent les soins en cas de complications ?',
                answer: 'Vous serez étroitement surveillée - par exemple, examens plus fréquents ou séjours à l\'hôpital pour vous garder, vous et le bébé, en bonne santé.',
                categoryId: '4.3',
              ),
            ],
          ),
          ContentCategory(
            id: '4.4',
            title: 'Préparation à l\'accouchement & organisation',
            imageUrl: '',
            sectionId: 'chapter4',
            questions: [
              ContentQuestion(
                id: '4.4.1',
                question: 'Quand dois-je choisir un hôpital ?',
                answer: 'De préférence avant la 20e semaine - beaucoup d\'hôpitaux sont vite complets. Vous pouvez alors vous y inscrire pour l\'accouchement.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.2',
                question: 'Comment fonctionne l\'inscription pour l\'accouchement à l\'hôpital ?',
                answer: 'Vous vous inscrivez par téléphone ou en ligne. Certains hôpitaux vous invitent à une soirée d\'information ou organisent un entretien sur place.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.3',
                question: 'Qu\'y a-t-il de particulier dans une grossesse multiple ?',
                answer: 'Vous serez examinée plus fréquemment car les jumeaux ou plusieurs bébés présentent un risque plus élevé. L\'accouchement est souvent planifié plus soigneusement.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.4',
                question: 'Que comprend l\'examen final peu avant l\'accouchement ?',
                answer: 'Le médecin vérifie la position et le poids du bébé, les contractions, le col de l\'utérus et si tout est prêt pour l\'accouchement.',
                categoryId: '4.4',
              ),
              ContentQuestion(
                id: '4.4.5',
                question: 'Quelle est la différence entre les soins ambulatoires et hospitaliers ?',
                answer: 'Ambulatoire signifie que vous rentrez chez vous peu après l\'accouchement. Hospitalier signifie que vous restez à l\'hôpital quelques jours.',
                categoryId: '4.4',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter5',
        title: 'Préparation à l\'accouchement',
        imageUrl: '/assets/icons/chapter5.png',
        categories: [
          ContentCategory(
            id: '5.1',
            title: 'Débuter la préparation à l\'accouchement',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.1.1',
                question: 'Quand commencer à se préparer à l\'accouchement ?',
                answer: 'De préférence à partir de la 25e semaine de grossesse. Cela vous donne assez de temps pour vous préparer physiquement et mentalement.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.2',
                question: 'Qu\'est-ce qu\'un cours de préparation à l\'accouchement ?',
                answer: 'Dans ce cours, vous apprenez ce qui se passe pendant l\'accouchement, comment vous détendre et comment votre partenaire peut vous soutenir.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.3',
                question: 'Qu\'y apprend-on ?',
                answer: 'Vous apprenez des techniques de respiration, des positions d\'accouchement, des informations sur l\'accouchement, la période post-partum et comment gérer la douleur.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.4',
                question: 'Le partenaire a-t-il aussi besoin de préparation ?',
                answer: 'Oui, les partenaires peuvent aussi apprendre beaucoup - comment aider, soutenir et être présents pendant l\'accouchement.',
                categoryId: '5.1',
              ),
              ContentQuestion(
                id: '5.1.5',
                question: 'Quel rôle joue la sage-femme avant l\'accouchement ?',
                answer: 'Elle vous accompagne, répond aux questions, vous prépare à l\'accouchement et aide à réduire les peurs.',
                categoryId: '5.1',
              ),
            ],
          ),
          ContentCategory(
            id: '5.2',
            title: 'Questions pratiques & organisation',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.2.1',
                question: 'Que mettre dans la valise pour la maternité et quand la préparer ?',
                answer: 'Préparez-la environ 4 semaines avant votre date d\'accouchement. Incluez : vêtements, articles de toilette, documents, en-cas, essentiels pour bébé.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.3',
                question: 'Qu\'est-ce qu\'un plan de naissance - et comment l\'écrire ?',
                answer: 'Dans ce plan, vous notez vos souhaits pour l\'accouchement : par ex., médicaments contre la douleur, positions, qui doit être présent. C\'est une aide pour l\'équipe hospitalière.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.4',
                question: 'Qu\'est-ce qui est important pour choisir le lieu d\'accouchement ?',
                answer: 'Les facteurs importants sont la proximité, les installations, la gestion des urgences et votre intuition. Hôpital, maison de naissance ou domicile - tout est possible.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.5',
                question: 'Accouchement à l\'hôpital, en maison de naissance ou à domicile - qu\'est-ce qui me convient ?',
                answer: 'Cela dépend de votre santé, de vos souhaits et de votre sécurité. Parlez-en à votre médecin ou à votre sage-femme.',
                categoryId: '5.2',
              ),
              ContentQuestion(
                id: '5.2.6',
                question: 'Quel est le risque d\'un accouchement à domicile ?',
                answer: 'Il y a moins d\'équipement médical qu\'à l\'hôpital. En cas de complications, vous devez pouvoir vous rendre rapidement à l\'hôpital.',
                categoryId: '5.2',
              ),
            ],
          ),
          ContentCategory(
            id: '5.3',
            title: 'Préparation mentale & physique',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.3.1',
                question: 'Comment me préparer mentalement à l\'accouchement ?',
                answer: 'Parlez de vos peurs, informez-vous, pratiquez la relaxation et faites confiance à votre corps. Les cours et les conversations aident aussi.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.2',
                question: 'Que puis-je faire contre les peurs avant l\'accouchement ?',
                answer: 'Parlez à votre sage-femme, apprenez des techniques de relaxation et échangez avec d\'autres mères sur leurs expériences.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.3',
                question: 'Quelles méthodes de relaxation aident ?',
                answer: 'Les exercices de respiration, la méditation, les massages, la musique calme et le mouvement peuvent vous aider à rester calme et sereine.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.4',
                question: 'Quels signes indiquent que l\'accouchement est imminent ?',
                answer: 'Les signes comprennent : contractions régulières, rupture de la poche des eaux, perte du bouchon muqueux ou douleurs au dos. Alors ça pourrait bientôt commencer.',
                categoryId: '5.3',
              ),
              ContentQuestion(
                id: '5.3.5',
                question: 'Qu\'est-ce que l\'instinct de nidification ?',
                answer: 'Peu avant l\'accouchement, beaucoup de femmes ressentent le besoin de tout nettoyer et préparer - c\'est tout à fait normal.',
                categoryId: '5.3',
              ),
            ],
          ),
          ContentCategory(
            id: '5.4',
            title: 'Préparation physique & exercices',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.4.1',
                question: 'Quel rôle joue le mouvement en fin de grossesse ?',
                answer: 'Il renforce votre corps, favorise la circulation et peut vous aider à mieux dormir et à vous préparer à l\'accouchement.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.2',
                question: 'Quels exercices préparent à l\'accouchement ?',
                answer: 'Bons exemples : exercices du plancher pelvien, techniques de respiration, yoga léger ou exercices d\'étirement. Votre sage-femme vous montrera ce qui convient.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.3',
                question: 'Quelles positions d\'accouchement puis-je pratiquer ?',
                answer: 'Par exemple : à quatre pattes, accroupie, debout, couchée. Essayez ce qui vous fait du bien - votre corps vous guidera.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.4',
                question: 'Comment puis-je préparer mes muscles du plancher pelvien ?',
                answer: 'Avec des exercices spécifiques, vous entraînez les muscles du bassin - ils aident pendant l\'accouchement et préviennent l\'incontinence urinaire ultérieure.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.5',
                question: 'Qu\'est-ce que le massage périnéal et à quoi sert-il ?',
                answer: 'Il rend le tissu plus élastique et peut aider à prévenir les déchirures périnéales pendant l\'accouchement. Vous pouvez commencer à partir de la 34e semaine.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.6',
                question: 'Que se passe-t-il lors de l\'acupuncture préparatoire à l\'accouchement ?',
                answer: 'De fines aiguilles sont placées à certains points. Cela est censé préparer le corps à l\'accouchement et soulager la douleur.',
                categoryId: '5.4',
              ),
              ContentQuestion(
                id: '5.4.7',
                question: 'Qu\'est-ce qu\'un monitoring et quand est-il pratiqué ?',
                answer: 'Un monitoring mesure les battements du cœur du bébé et vos contractions. Il est généralement fait régulièrement à partir de la 30e semaine.',
                categoryId: '5.4',
              ),
            ],
          ),
          ContentCategory(
            id: '5.5',
            title: 'Situations de préparation particulières',
            imageUrl: '',
            sectionId: 'chapter5',
            questions: [
              ContentQuestion(
                id: '5.5.1',
                question: 'Qu\'est-ce qui est différent avec les grossesses multiples dans la préparation ?',
                answer: 'L\'accouchement est planifié plus soigneusement, il y a plus de contrôles, et souvent une césarienne est nécessaire - votre hôpital vous aidera pour cela.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.2',
                question: 'Comment puis-je me préparer à un accouchement prématuré ?',
                answer: 'Discutez de tout avec votre médecin et l\'hôpital. Important : repos, surveillance étroite et informations sur les soins aux prématurés.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.3',
                question: 'Et si le bébé est en position de siège ?',
                answer: 'Parfois, le bébé peut encore se retourner. Il existe des exercices spéciaux ou une version céphalique externe réalisée par le médecin.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.4',
                question: 'Comment me préparer à une césarienne planifiée ?',
                answer: 'Vous serez bien informée. L\'hôpital vous explique tout et vous obtenez généralement un rendez-vous pour l\'opération à l\'avance.',
                categoryId: '5.5',
              ),
              ContentQuestion(
                id: '5.5.5',
                question: 'Qui m\'aide à me préparer si je suis seule ?',
                answer: 'Les sages-femmes, les centres de conseil ou les amis peuvent vous soutenir. Vous n\'êtes pas seule - il y a de l\'aide pour vous.',
                categoryId: '5.5',
              ),
            ],
          ),
        ],
      ),
      ContentSection(
        id: 'chapter6',
        title: 'L\'accouchement - à quoi s\'attendre',
        imageUrl: '/assets/icons/chapter6.png',
        categories: [
          ContentCategory(
            id: '6.1',
            title: 'Arrivée & admission',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.1.1',
                question: 'Quand dois-je me rendre à l\'hôpital ou à la maison de naissance ?',
                answer: 'Quand les contractions sont régulières, que votre poche des eaux se rompt ou que vous avez des douleurs, vous devriez vous y rendre.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.2',
                question: 'Que se passe-t-il lors de l\'admission pour l\'accouchement ?',
                answer: 'Vous serez examinée, on vous demandera comment vous allez, on fera un monitoring et on vérifiera où en est l\'accouchement.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.3',
                question: 'Quels examens sont faits au début ?',
                answer: 'Généralement un monitoring, une palpation de l\'abdomen, un examen vaginal et parfois une échographie.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.4',
                question: 'Qu\'est-ce que le col de l\'utérus et comment est-il contrôlé ?',
                answer: 'Le col de l\'utérus est la sortie de l\'utérus. On vérifie sa dilatation lors d\'un examen vaginal.',
                categoryId: '6.1',
              ),
              ContentQuestion(
                id: '6.1.5',
                question: 'Qu\'est-ce qu\'un monitoring et pourquoi est-il important ?',
                answer: 'Un monitoring mesure les battements du cœur de votre bébé et vos contractions. Cela montre comment va le bébé.',
                categoryId: '6.1',
              ),
            ],
          ),
          ContentCategory(
            id: '6.2',
            title: 'Soulagement de la douleur & méthodes d\'accouchement',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.2.1',
                question: 'Quels médicaments contre la douleur sont disponibles pendant l\'accouchement ?',
                answer: 'Il y a de nombreuses options : techniques de respiration, chaleur, massage, médicaments antidouleur, protoxyde d\'azote ou péridurale.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.2',
                question: 'Qu\'est-ce qu\'une péridurale ?',
                answer: 'Une péridurale est une injection dans le dos qui engourdit le bas du corps - ainsi, vous ne sentez presque plus les contractions.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.3',
                question: 'Qu\'est-ce qu\'une rachianesthésie ?',
                answer: 'Elle agit plus rapidement qu\'une péridurale et est souvent utilisée pour les césariennes planifiées.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.4',
                question: 'Qu\'est-ce qu\'un accouchement dans l\'eau et comment ça se passe ?',
                answer: 'Vous accouchez dans une baignoire spéciale. L\'eau chaude détend et peut réduire la douleur.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.5',
                question: 'Quelles méthodes naturelles de soulagement de la douleur existe-t-il ?',
                answer: 'Mouvement, techniques de respiration, massage, eau, tabouret d\'accouchement ou aide du partenaire - tout peut vous aider.',
                categoryId: '6.2',
              ),
              ContentQuestion(
                id: '6.2.6',
                question: 'Et si j\'ai peur de l\'accouchement ?',
                answer: 'Parlez-en avec votre sage-femme. Il existe des préparations à l\'accouchement, l\'hypnobirthing et du soutien pour vous.',
                categoryId: '6.2',
              ),
            ],
          ),
          ContentCategory(
            id: '6.3',
            title: 'Déroulement de l\'accouchement vaginal',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.3.1',
                question: 'Comment se déroule un accouchement vaginal - étape par étape ?',
                answer: 'D\'abord, le col de l\'utérus et l\'utérus s\'ouvrent. Puis vient la phase de poussée et enfin le bébé naît.',
                categoryId: '6.3',
              ),
              ContentQuestion(
                id: '6.3.2',
                question: 'Quelles positions puis-je prendre pendant l\'accouchement ?',
                answer: 'Debout, assise, à genoux, couchée - vous pouvez choisir ce qui est le plus confortable pour vous.',
                categoryId: '6.3',
              ),
              ContentQuestion(
                id: '6.3.3',
                question: 'Que se passe-t-il pendant la poussée ?',
                answer: 'Vous aidez activement à pousser le bébé dehors - guidée par la sage-femme ou le médecin.',
                categoryId: '6.3',
              ),
              ContentQuestion(
                id: '6.3.4',
                question: 'Que se passe-t-il immédiatement après la naissance du bébé ?',
                answer: 'Le bébé est placé sur votre ventre, le cordon ombilical est coupé, et vous délivrez généralement le placenta.',
                categoryId: '6.3',
              ),
            ],
          ),
          ContentCategory(
            id: '6.4',
            title: 'Conséquences physiques & soins',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.4.1',
                question: 'Qu\'est-ce qu\'une épisiotomie et quand est-elle pratiquée ?',
                answer: 'Une épisiotomie est une petite incision à l\'ouverture vaginale - elle n\'est faite que si nécessaire, par exemple si le bébé est en danger.',
                categoryId: '6.4',
              ),
              ContentQuestion(
                id: '6.4.2',
                question: 'Qu\'est-ce qu\'une déchirure périnéale ?',
                answer: 'Le périnée peut se déchirer pendant l\'accouchement - il guérit généralement bien et est suturé par le médecin immédiatement.',
                categoryId: '6.4',
              ),
              ContentQuestion(
                id: '6.4.3',
                question: 'Comment traite-t-on une déchirure périnéale ?',
                answer: 'La déchirure est suturée avec du fil après l\'accouchement, qui se dissout plus tard de lui-même. Les analgésiques aident à la guérison.',
                categoryId: '6.4',
              ),
              ContentQuestion(
                id: '6.4.4',
                question: 'Que devient le placenta après l\'accouchement ?',
                answer: 'Il est généralement expulsé peu après le bébé - c\'est ce qu\'on appelle la délivrance. Le médecin vérifie s\'il est complet.',
                categoryId: '6.4',
              ),
            ],
          ),
          ContentCategory(
            id: '6.5',
            title: 'Bébé & premier lien',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.5.1',
                question: 'Qu\'est-ce que le peau à peau après l\'accouchement ?',
                answer: 'Le peau à peau est le premier câlin avec votre bébé - il renforce votre lien et apporte sécurité et chaleur.',
                categoryId: '6.5',
              ),
              ContentQuestion(
                id: '6.5.2',
                question: 'Comment le bébé est-il examiné après la naissance ?',
                answer: 'Le médecin vérifie la respiration, le rythme cardiaque, les réflexes et l\'apparence - tout rapidement et avec douceur.',
                categoryId: '6.5',
              ),
              ContentQuestion(
                id: '6.5.3',
                question: 'Qu\'est-ce que le score d\'APGAR ?',
                answer: 'Il évalue l\'Apparence, le Pouls, la Grimace, l\'Activité et la Respiration - immédiatement après la naissance, puis après 5 et 10 minutes.',
                categoryId: '6.5',
              ),
            ],
          ),
          ContentCategory(
            id: '6.6',
            title: 'Situations particulières & complications',
            imageUrl: '',
            sectionId: 'chapter6',
            questions: [
              ContentQuestion(
                id: '6.6.1',
                question: 'Quel rôle joue la sage-femme pendant l\'accouchement ?',
                answer: 'Elle est la compagne la plus importante, vous soutient pendant les contractions, vous observe ainsi que le bébé et aide aux décisions.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.2',
                question: 'Qu\'est-ce qu\'un arrêt du travail ?',
                answer: 'Quand le col de l\'utérus cesse de se dilater ou que le bébé ne descend plus, on parle d\'un arrêt - des mesures sont alors prises.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.3',
                question: 'Que se passe-t-il lors d\'un accouchement par ventouse ?',
                answer: 'Une petite ventouse est fixée à la tête du bébé pour aider à la dernière partie de l\'accouchement - généralement sans danger pour l\'enfant.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.4',
                question: 'Quand un accouchement par forceps est-il nécessaire ?',
                answer: 'Si le bébé est en détresse ou doit être délivré rapidement, les forceps peuvent aider à le sortir doucement.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.5',
                question: 'Quand et comment pratique-t-on une césarienne ?',
                answer: 'Quand un accouchement normal n\'est pas possible ou qu\'il y a un risque. Le bébé est délivré par une incision abdominale.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.6',
                question: 'Quelle est la différence entre une césarienne planifiée et une césarienne d\'urgence ?',
                answer: 'Une césarienne planifiée a lieu avant le début du travail. Une césarienne d\'urgence se produit quand des complications surviennent pendant l\'accouchement.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.7',
                question: 'Que signifie un accouchement précipité ?',
                answer: 'C\'est un accouchement très rapide où tout se passe soudainement - c\'est rare mais généralement pas dangereux.',
                categoryId: '6.6',
              ),
              ContentQuestion(
                id: '6.6.8',
                question: 'Qu\'est-ce qu\'un accouchement ambulatoire ?',
                answer: 'Vous ne restez que quelques heures après l\'accouchement à l\'hôpital et rentrez ensuite chez vous - avec le soutien d\'une sage-femme.',
                categoryId: '6.6',
              ),
            ],
          ),
        ],
      ),
    ]);
  }
}